### ISSUE TITLE
Crash when opening Pocket feed

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1107]
## Steps to reproduce
1. Open tile
2. Open overlay and go to Pocket megatile
(May need to repeat these steps a few times)
(Also, this is not always reproducible - I don't see it when #1106 is happening)

### Expected behavior
Normal behavior, Pocket feed opens

### Actual behavior
Crash

```
2018-09-12 15:50:49.885 7871-7871/org.mozilla.tv.firefox.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.tv.firefox.debug, PID: 7871
    java.lang.IllegalStateException: browserOverlay must not be null
        at org.mozilla.focus.browser.BrowserFragment.updateOverlayIfVisible(BrowserFragment.kt:109)
        at org.mozilla.focus.browser.BrowserFragment.onUrlChanged(BrowserFragment.kt:99)
        at mozilla.components.browser.session.Session$$special$$inlined$observable$1$lambda$1.invoke(Session.kt:126)
        at mozilla.components.browser.session.Session$$special$$inlined$observable$1$lambda$1.invoke(Session.kt:20)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:106)
        at mozilla.components.browser.session.Session.notifyObservers(Session.kt)
        at mozilla.components.browser.session.Session.notifyObservers(Session.kt:250)
        at mozilla.components.browser.session.Session.access$notifyObservers(Session.kt:20)
        at mozilla.components.browser.session.Session$$special$$inlined$observable$1.afterChange(Delegates.kt:72)
        at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
        at mozilla.components.browser.session.Session.setUrl(Session.kt)
        at mozilla.components.browser.session.engine.EngineObserver.onLocationChange(EngineObserver.kt:18)
        at mozilla.components.browser.engine.system.SystemEngineView$createWebViewClient$1$onPageFinished$$inlined$let$lambda$1.invoke(SystemEngineView.kt:121)
        at mozilla.components.browser.engine.system.SystemEngineView$createWebViewClient$1$onPageFinished$$inlined$let$lambda$1.invoke(SystemEngineView.kt:106)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:106)
        at mozilla.components.concept.engine.EngineSession.notifyObservers(EngineSession.kt)
        at mozilla.components.browser.engine.system.SystemEngineSession.internalNotifyObservers$engine_system_release(SystemEngineSession.kt:238)
        at mozilla.components.browser.engine.system.SystemEngineView$createWebViewClient$1.onPageFinished(SystemEngineView.kt:120)
        at com.amazon.webview.awvclients.AmazonWebViewClient.onPageFinished(AmazonWebViewClient.java:95)
        at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:546)
        at com.android.webview.chromium.WebViewExtAmazonContentsClientAdapter.onPageFinished(WebViewExtAmazonContentsClientAdapter.java:18)
        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:201)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
2018-09-12 15:50:49.899 3446-3517/? W/ActivityManager:   Force finishing activity org.mozilla.tv.firefox.debug/org.mozilla.focus.MainActivity
```

### Device information

* Fire TV device: Pendant/Diamond, Cube (didn't test stick bc of #1087 )
* Firefox version: 25

**Comment by psymoon** [comment]
I've come across this yesterday, I will investigate
