### ISSUE TITLE
java.lang.IllegalStateException: Fragment BrowserFragment{a522f86} not attached to a context.

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1241]
via https://sentry.prod.mozaws.net/operations/firefox-tv/issues/4738557/

STR unknown, looks like our BrowserFragment is getting restored. **2 crashes on v2.2.0.2.**

```
java.lang.IllegalStateException: Fragment BrowserFragment{a522f86} not attached to a context.
    at android.support.v4.app.Fragment.requireContext(Fragment.java:614)
    at org.mozilla.focus.ext.FragmentKt.getRequireComponents(Fragment.kt:16)
    at org.mozilla.focus.browser.BrowserFragment.loadUrl(BrowserFragment.kt:319)
    at org.mozilla.focus.browser.BrowserFragment$onWebViewCreated$1.run(BrowserFragment.kt:232)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5491)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by mcomella** [comment]
This still only has two crashes: seems insignificant. Closing.
