### ISSUE TITLE
Move to new version of Activity.onCreateView

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1247]
i.e. https://developer.android.com/reference/android/app/Activity.html#onCreateView(android.view.View,%20java.lang.String,%20android.content.Context,%20android.util.AttributeSet)

The old implementation caused obscure crash bugs on fennec ([see bugs duped to this](https://bugzilla.mozilla.org/show_bug.cgi?id=1401779)) so we should move to the new one.

**Comment by unicorn-io** [comment]
I'll try my best to solve this!

**Comment by mcomella** [comment]
@unicorn-io Sorry I missed you on IRC! The code is in MainActivity: https://searchfox.org/mozilla-mobile/rev/5a56c1a6fc20f4eae318d378e717244a7e136824/firefox-tv/app/src/main/java/org/mozilla/tv/firefox/MainActivity.kt#206

For future reference, you should be able to find it with plain text search in Android Studio, on the command line, GitHub code search, etc.

**Comment by unicorn-io** [comment]
I have moved the version am I supposed to apply for pull request?

**Comment by mcomella** [comment]
@unicorn-io Yes, please open a pull request and (if GitHub lets you) flag me for review!

**Comment by unicorn-io** [comment]
@mcomella i have flaged you for review

**Comment by unicorn-io** [comment]
@mcomella I please review the changes

**Comment by mcomella** [comment]
Closed by https://github.com/mozilla-mobile/firefox-tv/pull/2295.

**Comment by mcomella** [comment]
This created a start-up crash on master and was backed out in https://github.com/mozilla-mobile/firefox-tv/commit/bdc868db6cbb2f1f76fb696ba8e17cf309de606a

**Comment by Baron-Severin** [comment]
I believe the issue is that the platform type was described as nonnull, while the activity will pass a null `parent` on startup.  I haven't verified, though.

**Comment by mcomella** [comment]
With the backed out PR, I get the following stack trace:
```kotlin
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter parent
        at org.mozilla.tv.firefox.MainActivity.onCreateView(Unknown Source:33)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1901)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2579)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2652)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2066)
        at org.mozilla.tv.firefox.MainActivity.onCreate(MainActivity.kt:67)
```

@unicorn-io We get a crash on startup and had to back out your changes: did you see this locally when you wrote the patch? Can you try to fix the issue and open a new PR?

**Comment by unicorn-io** [comment]
I will try to fix it.

**Comment by unicorn-io** [comment]
@mcomella i see no use of that parameter

**Comment by unicorn-io** [comment]
> 
> 
> I believe the issue is that the platform type was described as nonnull, while the activity will pass a null `parent` on startup. I haven't verified, though.

this seems to be the issue as per my checks

**Comment by mcomella** [comment]
Closed in https://github.com/mozilla-mobile/firefox-tv/pull/2356
