### ISSUE TITLE
Crash on Pocket reinstantiation

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1266]
## Steps to reproduce
(not 100% sure)
- From home
- Select Pocket feed
- Open other apps
- Take up a lot of memory (start videos, etc)
- Reopen FFTV

### Expected behavior
- Pocket feed resumes

### Actual behavior
- Application crashes

### Additional information
- PocketFragment video data is set in `MainActivity#onCreate` via `Pocket#init`
- `Pocket.init` is called after `super.onCreate`
- If the PocketFragment before `Pocket.init` is called, the app can crash.  This doesn't normally happen because a user cannot select Pocket quickly enough to cause the error
- Moving `Pocket.init` to execute before `MainActivity.super.onCreate` should fix the issue

### Stack trace
```
10-08 14:53:58.927 3086-3086/org.mozilla.tv.firefox.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.tv.firefox.debug, PID: 3086
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.tv.firefox.debug/org.mozilla.focus.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property videosCache has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2367)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435)
        at android.app.ActivityThread.access$800(ActivityThread.java:160)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5491)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property videosCache has not been initialized
        at org.mozilla.focus.home.pocket.Pocket.getRecommendedVideos(Pocket.kt:84)
        at org.mozilla.focus.home.pocket.PocketVideoFragment.onCreate(PocketVideoFragment.kt:56)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3194)
        at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:184)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:355)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
        at org.mozilla.focus.locale.LocaleAwareAppCompatActivity.onCreate(LocaleAwareAppCompatActivity.java:36)
        at org.mozilla.focus.MainActivity.onCreate(MainActivity.kt:73)
        at android.app.Activity.performCreate(Activity.java:6010)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435) 
        at android.app.ActivityThread.access$800(ActivityThread.java:160) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5491) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

### Device information

* Fire TV device: Stick
* Firefox version: 496e4e0087c71adfe5c7691168f177410a2237fc

**Comment by athomasmoz** [comment]
@AaronMT were you able to reproduce this? This could be a general memory problem, but let's first see if we can reproduce.

**Comment by AaronMT** [comment]
Build: c6bb934ec13921d5d299423ed6d32c9a0bf62948
Device: 4K Stick.

Wasn't able to reproduce using the steps above. @levisacal can you reproduce on a basic TV stick?

**Comment by athomasmoz** [comment]
General memory concern and not reproducible on newer devices. Closing for now
