### ISSUE TITLE
[1364] #4: ClearSessionDataTest is failing (ClearDataTest)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1360]
## Steps to reproduce
- Run ClearSessionDataTest

### Expected behavior
It passes

### Actual behavior
It fails:
```
android.support.test.espresso.PerformException: Error performing 'single click - At Coordinates: 1367, 651 and precision: 16, 16' on view 'with id: android:id/button1'.
...
Caused by: android.support.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
```

Theories:
- Restarting the Activity (on clear data click) causes the click validation to fail
- Restarting the Activity breaks the SessionIdlingResource

### Device information
* Fire TV device: Android TV API 26 emulator
* Firefox version: v3.0+ master

**Comment by mcomella** [comment]
@Baron-Severin Please update us on the status of this bug.

**Comment by Baron-Severin** [comment]
We believed that this was failing because of a problem with the test, but it was due to an actual bug.  This bug was fixed in https://github.com/mozilla-mobile/firefox-tv/pull/1524.  Lesson learned, the tests don't help much if we don't take them seriously and verify that they're meaningful.  We'll do better next time.

However... this test is expanded as part of #1392.  It now checks that back/forward buttons enable properly after clearing data.  I have manually verified that this behavior is correct, but during tests our `IdlingResource` times out after navigating to the first page after clearing data (reproducible 100%).  It seems that `Session.loading` is never set to false, because `SystemEngineView#onPageFinished` is not called.  

I'm pretty early in the debugging process, don't have any more clues than that.

**Comment by AaronMT** [comment]
On a whim just wanted to see if this still fails pending any update, it does. Didn't see any actual feature breakage though/

```java
androidx.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:94)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:57)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:316)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:300)
at org.mozilla.tv.firefox.helpers.ext.ViewInteractionKt.assertIsEnabled(ViewInteraction.kt:20)
at org.mozilla.tv.firefox.ui.robots.NavigationOverlayRobot.assertCanGoBack(NavigationOverlayRobot.kt:51)
at org.mozilla.tv.firefox.ui.robots.NavigationOverlayRobot.assertCanGoBackForward(NavigationOverlayRobot.kt:54)
at org.mozilla.tv.firefox.ui.ClearDataTest$WHEN_data_is_cleared_THEN_back_and_forward_should_be_unavailable$13.invoke(ClearDataTest.kt:66)
at org.mozilla.tv.firefox.ui.ClearDataTest$WHEN_data_is_cleared_THEN_back_and_forward_should_be_unavailable$13.invoke(ClearDataTest.kt:20)
at org.mozilla.tv.firefox.ui.robots.BrowserRobot$Transition.openOverlay(BrowserRobot.kt:63)
at org.mozilla.tv.firefox.ui.ClearDataTest.WHEN_data_is_cleared_THEN_back_and_forward_should_be_unavailable(ClearDataTest.kt:65)
