### ISSUE TITLE
Clearing browsing history does not clear previously visited pages from the back button

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/firefox-tv#1503]
## Steps to reproduce
1) Browse to some websites.
2) Press the hamburger menu on your remote to bring up the start page.
3) Click select over the cog wheel for settings.
4) Select and hit "Clear all cookies and site data".
### Expected behavior
There should be no option to press the back button.
### Actual behavior
There is still an option to go back through history for the session.
### Device information

* Fire TV device: Fire Stick 4k
* Firefox version: 3.0.2.1

**Comment by mcomella** [comment]
Note: we had a test to cover this behavior but it's failing: #1360.

**Comment by mcomella** [comment]
Possible issues:
- We could have broken the switch to clear data on the active WebView
- iirc, we added state restoration (when OOM): that could be interfering

**Comment by AaronMT** [comment]
Maybe related. On dialog accept I see:

`2018-11-15 13:45:11.379 4083-4083/org.mozilla.tv.firefox.debug W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.isDestroyed(AwContents.java:1262)
        at org.chromium.android_webview.AwContents.isDestroyedOrNoOperation(AwContents.java:1192)
        at org.chromium.android_webview.AwContents.evaluateJavaScript(AwContents.java:2259)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(WebViewChromium.java:592)
        at com.android.webview.chromium.WebViewExtAmazon.evaluateJavaScript(WebViewExtAmazon.java:55)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1053)
        at org.mozilla.tv.firefox.ext.EngineViewKt.evalJS(EngineView.kt:59)
        at org.mozilla.tv.firefox.webrender.FocusedDOMElementCache.restore(FocusedDOMElementCache.kt:21)
        at org.mozilla.tv.firefox.ext.EngineViewKt$setupForApp$1$1.run(EngineView.kt:47)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)`

**Comment by mcl21014** [comment]
Seems to be fixed in the latest version of 3.1. Someone should close this.

**Comment by AaronMT** [comment]
Yep fixed in another issue. Thanks for verifying.
