### ISSUE TITLE
Clear data doesn't clear data

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1517]
## Steps to reproduce
From home screen
- Open any pinned tile
- Open menu
- Open settings
- Clear data & return to home screen

### Expected behavior
- URL bar should be empty
- Back, forward, refresh, pin, and desktop mode buttons should be disabled
- Hitting the menu button should do nothing

### Actual behavior
- URL bar contains URL from previously selected tile
- Back, forward, refresh, pin, and desktop mode buttons are enabled
- Hitting the menu button opens the browser

### Device information

* Fire TV device: Cube
* Firefox version: 056c157218683ce4f03d1f53ababed4205bd643c

**Comment by AaronMT** [comment]
Maybe related. On dialog accept I see:

`2018-11-15 13:45:11.379 4083-4083/org.mozilla.tv.firefox.debug W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.isDestroyed(AwContents.java:1262)
        at org.chromium.android_webview.AwContents.isDestroyedOrNoOperation(AwContents.java:1192)
        at org.chromium.android_webview.AwContents.evaluateJavaScript(AwContents.java:2259)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(WebViewChromium.java:592)
        at com.android.webview.chromium.WebViewExtAmazon.evaluateJavaScript(WebViewExtAmazon.java:55)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1053)
        at org.mozilla.tv.firefox.ext.EngineViewKt.evalJS(EngineView.kt:59)
        at org.mozilla.tv.firefox.webrender.FocusedDOMElementCache.restore(FocusedDOMElementCache.kt:21)
        at org.mozilla.tv.firefox.ext.EngineViewKt$setupForApp$1$1.run(EngineView.kt:47)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)`
