### ISSUE TITLE
Can't play LiveNation media player

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1571]
On release, trying to play the firefoxconcerts.livenation.com media player results in a crash on release (probably due to Amazon watchdog killing the app for a dead webview), and making the webview unresponsive on debug.

This could just be a webview chromium bug - I noticed that the ad plays on Silk, but doesn't stream.

Note, this might not be actionable, and maybe a WONTFIX because the event will be over soon anyway.

Release logs:
```
2018-12-11 19:10:49.915 3791-3823/? I/chromium: [INFO:HTMLMediaElement.cpp(2462)] Play video at:0
2018-12-11 19:10:51.022 3791-3823/? I/chromium: [INFO:render_frame_impl.cc(2948)] Use WMPA = 1
2018-12-11 19:10:51.023 3791-3823/? I/chromium: [INFO:render_frame_impl.cc(6845)] Creating WMPA with ExoPlayer
2018-12-11 19:10:51.050 4120-5602/? D/WakeWordService: DecoderID=WakeWordService_input_decoder: recognition_id=WakeWordService_input_decoder-7: Observed consecutive frames of digital silence: 2
2018-12-11 19:10:51.058 3791-3823/? I/chromium: [INFO:amazon_webmediaplayer_android.cc(64)] AmazonWebMediaPlayerAndroid (WMPA) is created
2018-12-11 19:10:51.128 3548-3548/? I/chromium: [INFO:CONSOLE(5)] "00:00:00.000 INFO: Log: Log times are relative.  Starting at UTC: 1544584251102", source:  (5)
2018-12-11 19:10:51.129 3548-3548/? I/chromium: [INFO:CONSOLE(5)] "00:00:00.000 INFO: AssetPlayerBase: Wowza Player 1.1.13 build:8693 (javascript)", source:  (5)
2018-12-11 19:10:51.131 3548-3548/? I/chromium: [INFO:CONSOLE(5)] "00:00:00.028 INFO: AssetPlayerBase: License Key: PTRL1-XXXXX-XXXXX-XXXXX-XXXXX-DAJMR", source:  (5)
2018-12-11 19:10:51.154 3548-3548/? I/chromium: [INFO:CONSOLE(5)] "00:00:00.051 INFO: AssetPlayerBase: init", source:  (5)
2018-12-11 19:10:51.381 3548-3548/? I/chromium: [INFO:CONSOLE(5)] "00:00:00.279 INFO: AssetPlayerBase: prepare", source:  (5)
2018-12-11 19:10:51.498 4107-4791/? D/Vizzini:MediaSessionLib.MediaSessionControllerStateMgr: Playback State Changed org.mozilla.tv.firefox
2018-12-11 19:10:51.498 3715-4052/? V/Avrcp: MediaController playback changed: PlaybackState {state=2, position=0, buffered position=0, speed=0.0, updated=117409077, actions=822, custom actions=[], active item id=-1, error=null}
2018-12-11 19:10:51.500 3715-4052/? V/Avrcp: updatePlaybackState (1): old=PlaybackState {state=2, position=0, buffered position=0, speed=0.0, updated=117407237, actions=822, custom actions=[], active item id=-1, error=null}(2), new=PlaybackState {state=2, position=0, buffered position=0, speed=0.0, updated=117409077, actions=822, custom actions=[], active item id=-1, error=null}(2)
2018-12-11 19:10:51.500 3715-4052/? D/Avrcp: sendPlayPosNotificationRsp: Not registered or requesting.
2018-12-11 19:10:51.635 3548-3548/? I/chromium: [INFO:amazon_media_player_manager.cc(122)] OnInitialize create AmazonMediaPlayer (Exoplayer)
2018-12-11 19:10:51.636 3548-3548/? I/chromium: [INFO:amazon_media_player_bridge.cc(100)] Creating AmazonSampleSource for MSE playback
2018-12-11 19:10:51.637 3791-3823/? I/chromium: [INFO:render_frame_impl.cc(2948)] Use WMPA = 0
2018-12-11 19:10:51.637 3791-3823/? I/chromium: [INFO:amazon_main_delegate.cc(150)] Using WMPI with MediaPlayerRenderer for MSE-EXO pipeline
2018-12-11 19:10:51.637 3791-3823/? I/chromium: [INFO:render_frame_impl.cc(3048)] Use MediaPlayerRenderer = 1
2018-12-11 19:10:51.637 3791-3823/? I/chromium: [INFO:amazon_webmediaplayer_impl.cc(43)] AmazonWebMediaPlayerImpl (WMPI) is created
2018-12-11 19:10:51.640 3791-3823/? I/chromium: [INFO:amazon_renderer_surface_view_manager.cc(35)] Sending external surface creation request to browser
2018-12-11 19:10:51.676 3548-3828/? E/cr_MediaResource: Error configuring data source: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
    java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
        at android.media.MediaMetadataRetriever._setDataSource(Native Method)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:97)
        at org.chromium.content.browser.MediaResourceGetter.configure(MediaResourceGetter.java:5406)
        at org.chromium.content.browser.MediaResourceGetter.extractMediaMetadata(MediaResourceGetter.java:1139)
2018-12-11 19:10:51.676 3548-3828/? E/cr_MediaResource: Unable to configure metadata extractor
2018-12-11 19:10:51.696 3548-3548/? I/AMPEXO1Factory: createMediaPlayer : 3.0.0 AMPEXO1IMPL Version : 4.0.2 (for Exo 1.5.9) with Config = ExoPlayerSetupConfig{mMinBufferMs =3000, mMinRebufferMs =5000, mMaxDroppedFrameCountToNotify =15, mEnableCrossProtocolRedirection =false, mEnableTunnelModePlayback =false, mMaxRetriesOnConnectionError =2, mEnableEpochTimeInLive =false, mUsePsipCsdForCaptions =false}
2018-12-11 19:10:51.709 3548-3548/? I/StateMachineImplBase: Instantiating and initializing state machine. setup = ExoPlayerSetupConfig{mMinBufferMs =3000, mMinRebufferMs =5000, mMaxDroppedFrameCountToNotify =15, mEnableCrossProtocolRedirection =false, mEnableTunnelModePlayback =false, mMaxRetriesOnConnectionError =2, mEnableEpochTimeInLive =false, mUsePsipCsdForCaptions =false}
2018-12-11 19:10:51.719 3548-3548/? I/ExoPlayerImpl: Init 1.5.9
```

Debug logs:
```
2018-12-11 19:22:04.910 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:HTMLMediaElement.cpp(2462)] Play video at:0
2018-12-11 19:22:05.034 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:render_frame_impl.cc(2948)] Use WMPA = 0
2018-12-11 19:22:05.037 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:render_frame_impl.cc(3048)] Use MediaPlayerRenderer = 0
2018-12-11 19:22:05.051 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:amazon_webmediaplayer_impl.cc(43)] AmazonWebMediaPlayerImpl (WMPI) is created
2018-12-11 19:22:05.089 5009-5009/org.mozilla.tv.firefox.debug I/chromium: [INFO:CONSOLE(512)] "Uncaught TypeError: window.livestream_player.onCompleted is not a function", source:  (512)
2018-12-11 19:22:05.089 5009-5009/org.mozilla.tv.firefox.debug I/chromium: [INFO:CONSOLE(567)] "Uncaught TypeError: window.livestream_player.onReady is not a function", source:  (567)
2018-12-11 19:22:05.247 5009-5009/org.mozilla.tv.firefox.debug W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 5009
2018-12-11 19:22:05.291 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:amazon_renderer_surface_view_manager.cc(35)] Sending external surface creation request to browser
2018-12-11 19:22:05.422 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:amazon_renderer_surface_view_manager.cc(63)] Active external surface changed: 1
2018-12-11 19:22:05.429 3595-4281/? I/AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioMix
2018-12-11 19:22:05.431 4154-4154/? I/OZ-DCS:WakeLockReceiver: Posting wakelock event on feed bus: [key]: amazon.intent.action.WAKELOCK_ACQUIRED [uid]: 1041 [pid]: 0 [tag]: AudioMix
2018-12-11 19:22:05.433 3595-4274/? I/AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioIn
2018-12-11 19:22:05.433 3595-4274/? I/AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioMix
2018-12-11 19:22:05.434 3595-4274/? I/AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioIn
2018-12-11 19:22:05.435 5009-5075/org.mozilla.tv.firefox.debug D/AudioTrack: min buf count is limited to 2 times HAL buf
2018-12-11 19:22:05.436 4154-4154/? I/OZ-DCS:WakeLockReceiver: Posting wakelock event on feed bus: [key]: amazon.intent.action.WAKELOCK_ACQUIRED [uid]: 1041 [pid]: 0 [tag]: AudioIn
2018-12-11 19:22:05.445 4154-4154/? I/OZ-DCS:WakeLockReceiver: Posting wakelock event on feed bus: [key]: amazon.intent.action.WAKELOCK_ACQUIRED [uid]: 1041 [pid]: 0 [tag]: AudioMix
2018-12-11 19:22:05.461 5009-5075/org.mozilla.tv.firefox.debug D/AudioTrack: min buf count is limited to 2 times HAL buf
2018-12-11 19:22:05.464 5009-5075/org.mozilla.tv.firefox.debug D/AudioTrack: min buf count is limited to 2 times HAL buf
2018-12-11 19:22:05.470 4154-4154/? I/OZ-DCS:WakeLockReceiver: Posting wakelock event on feed bus: [key]: amazon.intent.action.WAKELOCK_RELEASED [uid]: 1041 [pid]: 0 [tag]: AudioIn
2018-12-11 19:22:05.491 4154-4154/? I/OZ-DCS:ModeLogger: OZ-DMC New ModeStateEvent: Current<all>: FIRE_TV [name : VIDEO_PAYBACK_PROVIDER time: 118026349 payload: {"function_":"Repeat","time_from_boot_":"32:47:06","now_from_boot_":"32:48:03","now_timestamp_":118083068,"time_absolute_":"19:21:08.769","lasting_time_":"infinite","metadata: ":"{\"action\":\"set\",\"delay\":0,\"inMode\":[\"tv\"],\"time\":0,\"toMode\":\"tv\"}"}]
2018-12-11 19:22:05.558 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:render_frame_impl.cc(2948)] Use WMPA = 0
2018-12-11 19:22:05.558 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:render_frame_impl.cc(3048)] Use MediaPlayerRenderer = 0
2018-12-11 19:22:05.558 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:amazon_webmediaplayer_impl.cc(43)] AmazonWebMediaPlayerImpl (WMPI) is created
2018-12-11 19:22:05.559 5009-5083/org.mozilla.tv.firefox.debug I/chromium: [INFO:amazon_renderer_surface_view_manager.cc(35)] Sending external surface creation request to browser
2018-12-11 19:22:05.608 3265-3356/? I/AUDIOALG: asyncProcess : process @@@
2018-12-11 19:22:05.613 3265-3356/? I/AUDIOALG: RefDlyEstimation: maxRxy 0.000000 maxPos 0
2018-12-11 19:22:05.613 3265-3356/? I/AUDIOALG: asyncProcess : waiting...
2018-12-11 19:22:05.649 5009-5075/org.mozilla.tv.firefox.debug I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
2018-12-11 19:22:05.655 3265-3368/? W/AudioFlinger: createTrack_l(): mismatch between requested flags (00000104) and output flags (00000002)
2018-12-11 19:22:05.656 3265-3368/? D/AudioFlinger: min buf count is limited to 2 times HAL buf
2018-12-11 19:22:05.661 5009-5075/org.mozilla.tv.firefox.debug W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 1540
2018-12-11 19:22:05.661 5009-5075/org.mozilla.tv.firefox.debug D/AudioTrack: Client defaulted notificationFrames to 513 for frameCount 1540
2018-12-11 19:22:05.699 3595-4245/? I/MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10226/5009 clientId=com.amazon.media.AmazonAudioManager@5bf2531org.chromium.content.browser.AudioFocusDelegate@49df416 req=3 flags=0x0
2018-12-11 19:22:05.704 3265-3359/? I/DolbyAudioHwDeviceProxy: resumeDownstream() for device:0x400
```

**Comment by liuche** [comment]
Waiting for Loren to get some more info from LiveNation on this video player and stream.

**Comment by liuche** [comment]
More logs here: https://gist.github.com/liuche/85ec240b719f522bcacd38bd5c182ecd

**Comment by athomasmoz** [comment]
Closing. Captured by #1577 ticket
