### ISSUE TITLE
NPE in ViewGroup in dispatchWindowVisibilityChanged

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1727]
## Steps to reproduce
No clear steps for repro, but here's the Sentry report: https://sentry.prod.mozaws.net/operations/firefox-tv/issues/4893882/

It seems to be more significant in 3.1.3, 3.0.3, but the graph is also indicating more crashes in 3.2.5

* Fire TV device: ?
* Firefox version: 3.1.3, 3.0.3, 3.2.5

Further notes from @Baron-Severin:
Possibly related to clearing data while a video is playing: https://stackoverflow.com/a/43763316

**Comment by mcomella** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchWindowVisibilityChanged(int)' on a null object reference
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1177)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1354)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1090)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5988)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:781)
    at android.view.Choreographer.doCallbacks(Choreographer.java:592)
    at android.view.Choreographer.doFrame(Choreographer.java:560)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:767)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5597)
```

This looks like it happens in the framework. :(

**Comment by mcomella** [comment]
Might be useful to identify when this started happening and so what changes could have caused this.

**Comment by cpeterso** [comment]
Sentry reports that we're still seeing about 2,000 of these crashes every day:

https://sentry.prod.mozaws.net/operations/firefox-tv/issues/4893882/
