### ISSUE TITLE
OnboardingLaunchTest fails: wait for SessionLoadedIdlingResources to become idle timed out

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1748]
```
android.support.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1536)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:88)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:51)
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312)
at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:297)
at org.mozilla.tv.firefox.ui.screenshots.OnboardingLaunchTest.firstLaunchScreen(OnboardingLaunchTest.java:77)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

This happens on master, 1bb2ae87840035827f2929a89790093c7a29db63, on my Android TV emulator, 1080p Android 26.

**Comment by mcomella** [comment]
This also fails on v3.2.6.1: maybe this broke at some point during the refactor.

**Comment by mcomella** [comment]
This passes on v3.2 so failure occurs somewhere between v3.2 and v3.2.6.1.

**Comment by mcomella** [comment]
Note: this fails on an emulator.

**Comment by mcomella** [comment]
In `SessionLoadingIdlingResource.onIdleNow`, I added the line, `Log.e("lol", "$session ${session?.loading}")`: it appears that `session?.loading` returns `true` for `firefox:home` forever.

**Comment by mcomella** [comment]
Running the app directly, `onLoadingStateChanged` changes from false (initial value) to true to false in the same use cases. 🤔

**Comment by mcomella** [comment]
Please verify that this test, and #1755, are passing after this change lands. If #1755 passes, you can close it too.

**Comment by mcomella** [comment]
@npark-mozilla @levisacal ^ Might be better to verify that we fixed these tests sooner rather than later.

**Comment by npark-mozilla** [comment]
@mcomella,  @levisacal will verify it on tomorrow's ui test run.

**Comment by levisacal** [comment]
@mcomella @npark-mozilla The OnboardingLaunchTest passed on 4k and Basic Stick device on the latest commit fed9081fef58096f05179505e77d587687aa2086
