### ISSUE TITLE
UI Test exitAppByBackButtonTest failed on 4k

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1753]
## Steps to reproduce

Run UI Test in Android Studio, on 4K Pendant Fire TV device

### Expected behavior

Test passes

### Actual behavior

exitAppByBackButtonTest failed

### Device information

* Fire TV device:  4K Pendant Fire TV
* Firefox version: latest master

org.mozilla.tv.firefox.ui.DesktopModeTest

32.26 s
error
desktopModeTest
```
android.support.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out 
at dalvik.system.VMStack.getThreadStackTrace(Native Method) 
at java.lang.Thread.getStackTrace(Thread.java:1566) 
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:88) 
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:51) 
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312) 
at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:297) 
at org.mozilla.tv.firefox.helpers.ext.ViewInteractionKt.assertIsChecked(ViewInteraction.kt:21) 
at org.mozilla.tv.firefox.ui.robots.NavigationOverlayRobot$Transition.assertCanTurnDesktopModeOn(NavigationOverlayRobot.kt:126) 
at org.mozilla.tv.firefox.ui.robots.NavigationOverlayRobot$Transition.turnDesktopModeOn(NavigationOverlayRobot.kt:129) 
at org.mozilla.tv.firefox.ui.DesktopModeTest.desktopModeTest(DesktopModeTest.kt:43) 
at java.lang.reflect.Method.invoke(Native Method) 
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) 
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) 
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) 
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527) 
at org.junit.rules.RunRules.evaluate(RunRules.java:20) 
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) 
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) 
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) 
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) 
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) 
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) 
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) 
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) 
at org.junit.runners.ParentRunner.run(ParentRunner.java:363) 
at org.junit.runners.Suite.runChild(Suite.java:128) 
at org.junit.runners.Suite.runChild(Suite.java:27) 
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) 
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) 
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) 
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) 
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) 
at org.junit.runners.ParentRunner.run(ParentRunner.java:363) 
at org.junit.runner.JUnitCore.run(JUnitCore.java:137) 
at org.junit.runner.JUnitCore.run(JUnitCore.java:115) 
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56) 
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384) 
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1937) 
```

**Comment by npark-mozilla** [comment]
This failure does not occur on base tv stick, only able to repro on 4K pendant.

**Comment by mcomella** [comment]
@npark-mozilla How often do we see UI test failures on some devices but not others? I'm trying to get a better sense of the UI test failures we've been having.

**Comment by npark-mozilla** [comment]
@mcomella So this failure is happening consistently on @levisacal 's 4K pendant - but I have never been able to repro this on my cube or base stick.  It also passes consistently on @levisacal 's tv stick

**Comment by mcomella** [comment]
See also #1748 #1755

**Comment by levisacal** [comment]
@npark-mozilla @mcomella The Test is still failing on the 4k device on the latest commit fed9081

**Comment by Baron-Severin** [comment]
I'm not able to reproduce on our office 4k (Pendant running Fire OS 6.2.5.3 (NS6253/1431)).  The included stack trace looks like it comes from `desktopModeTest`, but that's passing on this device as well.  Is your failure rate 100% on these @levisacal?

**Comment by levisacal** [comment]
Actually the DesktopModeTest has passed. I have attached the test report to this issue for more information
[All_Tests_31Jan2019_FireTV4k.pdf](https://github.com/mozilla-mobile/firefox-tv/files/2826973/All_Tests_31Jan2019_FireTV4k.pdf)

**Comment by levisacal** [comment]
Strangely, on the latest commit 754babd20c86f920780d602756553b8854b467d8 of the master, this test is now failing on the Basic Stick and 4k device its passed. Attached the test report for the basic stick device also. 
[BasicStickTestResults.pdf](https://github.com/mozilla-mobile/firefox-tv/files/2828437/BasicStickTestResults.pdf)

**Comment by AaronMT** [comment]
This is failing on Bitbar Cloud devices too.

Disable?

**Comment by kglazko** [comment]
@AaronMT Same error as above with session idling? Or different?

**Comment by AaronMT** [comment]
This continues to fail on Bitbar Cloud testing on the 4K 

`java.lang.AssertionError at org.junit.Assert.fail(Assert.java:86
 at org.junit.Assert.assertTrue(Assert.java:41
 at org.junit.Assert.assertTrue(Assert.java:52
 at org.mozilla.tv.firefox.ui.robots.NavigationOverlayRobot.assertActivityFinishing(NavigationOverlayRobot.kt:77
 at org.mozilla.tv.firefox.ui.BasicNavigationTest$exitAppByBackButtonTest$1.invoke(BasicNavigationTest.kt:134
 at org.mozilla.tv.firefox.ui.BasicNavigationTest$exitAppByBackButtonTest$1.invoke(BasicNavigationTest.kt:24
 at org.mozilla.tv.firefox.ui.robots.NavigationOverlayRobotKt.navigationOverlay(NavigationOverlayRobot.kt:196
 at org.mozilla.tv.firefox.ui.BasicNavigationTest.exitAppByBackButtonTest(BasicNavigationTest.kt:132
 at java.lang.reflect.Method.invoke(Native Method`

**Comment by kglazko** [comment]
See https://github.com/mozilla-mobile/firefox-tv/commit/bffb74fb4ffffca68cd083a4eb621800027a5966
