### ISSUE TITLE
WebViewCacheTest is broken on master

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1801]
Something to do with `initDefaultUserAgent`:

`java.lang.UnsupportedOperationException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:241)
	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
	at mozilla.components.browser.engine.system.SystemEngine$Companion.initDefaultUserAgent(SystemEngine.kt:111)
	at mozilla.components.browser.engine.system.SystemEngine$Companion.access$initDefaultUserAgent(SystemEngine.kt:103)
	at mozilla.components.browser.engine.system.SystemEngine.<init>(SystemEngine.kt:30)
	at org.mozilla.tv.firefox.webrender.WebRenderComponents$engine$2.invoke(WebRenderComponents.kt:28)
	at org.mozilla.tv.firefox.webrender.WebRenderComponents$engine$2.invoke(WebRenderComponents.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.mozilla.tv.firefox.webrender.WebRenderComponents.getEngine(WebRenderComponents.kt)
	at org.mozilla.tv.firefox.webrender.WebViewCache$getWebView$2.invoke(WebViewCache.kt:68)
	at org.mozilla.tv.firefox.webrender.WebViewCache.getWebView(WebViewCache.kt:79)
	at org.mozilla.tv.firefox.webrender.WebViewCacheTest.getWebView(WebViewCacheTest.kt:53)
	at org.mozilla.tv.firefox.webrender.WebViewCacheTest.GIVEN cached WebView has a parent WHEN WebView is returned THEN WebView should be removed from parent(WebViewCacheTest.kt:42)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:600)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)`

**Comment by Baron-Severin** [comment]
It looks like this was introduced in 7f57f23c1 as part of #1789.  It's troubling that this got through CI, and it looks like two more PRs landed after this one.
