### ISSUE TITLE
Fix initialization errors when calling `buildActivity(MainActivity` in robolectric

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2367]
### Vision statement / What / Requirements
Currently, we have two platforms for testing: off-device tests and on-device tests. Unfortunately, we're forced to run all integration tests on-device – which take a long time to write, take a long time to run, and are hard to maintain. We can't write off-device tests for them because our MainActivity fails to initialize when using robolectric. The code that fails:
```kotlin
@RunWith(RobolectricTestRunner::class)
class MainActivityTest {

    private lateinit var controller: ActivityController<MainActivity>

    @Before
    fun setUp() {
        controller = Robolectric.buildActivity(MainActivity::class.java)
            .create()
            .start()
    }

    @Test
    fun `WHEN onStart is called THEN `() {
        controller.get()
    }
}
```

And the error it fails with:
```
java.lang.UnsupportedOperationException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:241)
	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
	at mozilla.components.browser.engine.system.SystemEngine$Companion.initDefaultUserAgent(SystemEngine.kt:111)
	at mozilla.components.browser.engine.system.SystemEngine$Companion.access$initDefaultUserAgent(SystemEngine.kt:103)
	at mozilla.components.browser.engine.system.SystemEngine.<init>(SystemEngine.kt:30)
	at org.mozilla.tv.firefox.webrender.WebRenderComponents$engine$2.invoke(WebRenderComponents.kt:35)
	at org.mozilla.tv.firefox.webrender.WebRenderComponents$engine$2.invoke(WebRenderComponents.kt:22)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.mozilla.tv.firefox.webrender.WebRenderComponents.getEngine(WebRenderComponents.kt)
```

The problem is that `WebSettings` is not mocked by robolectric so we can't call into it.

However, **I discovered an easy fix.** If we override `SystemEngine.defaultUserAgent` before creating the activity, the tests pass. This bug is to utilize this quick fix.

### Impact
Devs will no longer be blocked when trying to write tests `MainActivity` or other integration tests. This will allow us to cover more of our code with an easy and quick (to write and run) style of testing.

For example, had this been working in #2325, we could have replaced a manual TestRail test case we added with a few unit tests that would have taken only a few hours (or less) to write, saving much more time from QA in the long run.

### Acceptance criteria
- [x] `Robolectric.buildActivity` can be used to write tests

**Comment by mcomella** [comment]
After this issue, it's still difficult to write Robolectric tests because we can't provide fake objects: I filed https://github.com/mozilla-mobile/firefox-tv/issues/2369 to address this.

**Comment by mcomella** [comment]
This is waiting for review. The review was deprioritized in favor of higher priority work.

**Comment by mcomella** [comment]
QA: this refactors code so we can write additional styles of test. afaik, nothing needs to be done.
