### ISSUE TITLE
OnErrorNotImplementedException crash in ChannelRepo.loadBlackList when trying to delete a recent added pin from Tile section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2436]
## Steps to reproduce
1. Launch FF for Fire TV.
2. Select the `Pinned Tiles`.
3. Select the last tile(or any tile).
4. Delete them until `YouTube` tile remains.
5. Open `YouTube` tile.
6. Tap on the menu button(the FF menu overview is displayed).
7. Select the last tile `YouTube` and delete it.
8. Tap on the menu button(YouTube home screen is displayed).
9. Tap menu button again and pin the YouTube URL.
10. All the tiles are restored and the newly YouTube tile is added to the section.
11. Select few tiles and delete them and then delete the pinned site.

### Expected behavior
The deleted tiles are deleted including the newly pinned site.
### Actual behavior
When deleting the pinned site, FF for fire tv crashes.
### Device information
* Fire TV device: **`Fire Stick 2nd Gen.`**
* Latest affected Firefox version: **`FF for Fire TV 3.1.1-LAT1`**
* Earliest affected Firefox version: **`FF for Fire TV 3.1.1-LAT1`**
* Turbo Mode: **`On and Off`**
### Notes
For more details please see the [video](https://drive.google.com/file/d/15AKtMmoCRlZgBZlxPwuydvODx7m9wqSC/view?usp=sharing) 
[log_crash.txt](https://github.com/mozilla-mobile/firefox-tv/files/3290049/log_crash.txt)
Please note that this is with a 100% reproducible

**Comment by abodea** [comment]
```css
06-14 10:47:42.656 13552-13552/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.tv.firefox, PID: 13552
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | kotlin.NotImplementedError: other types shouldn't be able remove tiles
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at io.reactivex.internal.operators.observable.ObservableHide$HideDisposable.onNext(ObservableHide.java:67)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at org.mozilla.tv.firefox.channels.DefaultChannelAdapter$setRemoveOnLongClickListener$1$1.onClick(DefaultChannelAdapter.kt:118)
        at android.view.View.performClick(View.java:5047)
        at android.view.View.onKeyUp(View.java:9301)
        at android.widget.TextView.onKeyUp(TextView.java:5959)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2687)
        at android.view.View.dispatchKeyEvent(View.java:8683)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2405)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1738)
        at android.app.Dialog.dispatchKeyEvent(Dialog.java:778)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2320)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4088)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4038)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3736)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3627)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3793)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3627)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3769)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3930)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2206)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1849)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1840)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2183)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
    	at andr
06-14 10:47:42.656 13552-13552/? I/AndroidRuntime: To Report FATAL to activityManagerService
06-14 10:47:42.658 987-2682/? I/ActivityManager: handleApplicationCrash```

**Comment by abodea** [comment]
https://github.com/ReactiveX/RxJava/wiki/Error-Handling

**Comment by abodea** [comment]
Also, please note that even on a fresh install when adding a simple pin and trying to delete it FF crashes.

**Comment by athomasmoz** [comment]
> All the tiles are restored and the newly YouTube tile is added to the section.
Sounds like this is the issue. All the pinned tiles shouldn't be restored when you re-pin YouTube

@abodea Did you try this on the currently live release? I didn't think we made any changes to pinned tiles this week, so I'm curious if it's a regression

**Comment by devinreams** [comment]
Sentry issue: [FIREFOX-TV-53A](https://sentry.prod.mozaws.net/operations/firefox-tv/issues/5947996/)

**Comment by athomasmoz** [comment]
Confirmed this is a regression in 3.11

**Comment by abodea** [comment]
Hello @athomasmoz yes I verified this issue on the latest release `3.10` but I couldn't reproduce it. 
The tiles didn't restored and when I deleted the pinned tile, FF didn't crashed. I just re-checked 3 times with fresh install on `3.10`.
