### ISSUE TITLE
Crash when last tile in a channel is deleted

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2444]
## Steps to reproduce
- Delete all tiles from News channel (or any channel other than Pinned)

### Expected behavior
- Channel disappears

### Actual behavior
- App crashes

### Device information
* Fire TV device: 4k Stick
* Latest affected Firefox version: 0a4a117fc5524a87b62019f1ea2004885aaf1ee0 (current head of master)
* Earliest affected Firefox version: v3.11
* Turbo Mode: Both

**Comment by Baron-Severin** [comment]
### Stacktrace

```
2019-06-14 15:17:29.450 24337-24436/org.mozilla.tv.firefox.debug I/OpenGLRenderer: Initialized EGL, version 1.4
2019-06-14 15:17:29.450 24337-24436/org.mozilla.tv.firefox.debug D/OpenGLRenderer: Swap behavior 2
2019-06-14 15:17:29.507 24337-24404/org.mozilla.tv.firefox.debug E/AmazonDevicePolicyManager: EnterpriseWhiteListedUrlManager class doesn't exist. java.lang.ClassNotFoundException: com.amazon.url.EnterpriseWhiteListedUrlManager
2019-06-14 15:17:29.511 24337-24337/org.mozilla.tv.firefox.debug E/cr_AWVDeploymentClient: Chromium Version = v59 key doesn't exist. So, default version config will be used.
2019-06-14 15:17:29.511 24337-24337/org.mozilla.tv.firefox.debug E/cr_AWVDeploymentClient: Default device config doesn't exist
2019-06-14 15:17:29.519 24337-24337/org.mozilla.tv.firefox.debug E/cr_AWVDeploymentClient: Chromium Version = v59 key doesn't exist. So, default version config will be used.
2019-06-14 15:17:29.519 24337-24337/org.mozilla.tv.firefox.debug E/cr_AWVDeploymentClient: Default device config doesn't exist
2019-06-14 15:17:29.520 24337-24337/org.mozilla.tv.firefox.debug I/WebViewExtAmazon: Appending switch enable-exo-sv-reset-workaround
2019-06-14 15:17:29.520 24337-24337/org.mozilla.tv.firefox.debug I/WebViewExtAmazon: Appending switch disable-mp4-mp3-routing-to-wmpa
2019-06-14 15:17:29.520 24337-24337/org.mozilla.tv.firefox.debug I/WebViewExtAmazon: Appending switch disable-hdr
2019-06-14 15:17:29.524 24337-24337/org.mozilla.tv.firefox.debug I/WebViewExtAmazon: Device supports 4k. Enabling 4k Mode
2019-06-14 15:17:29.524 24337-24337/org.mozilla.tv.firefox.debug I/WebViewExtAmazon: Display switched to 4k
2019-06-14 15:17:29.525 24337-24337/org.mozilla.tv.firefox.debug I/WebViewExtAmazon: Adjusting Device refresh rate to 60. Actual: 59.94
2019-06-14 15:17:29.526 24337-24337/org.mozilla.tv.firefox.debug I/WebViewExtAmazon: Max frame rate for media playback: 30.0
2019-06-14 15:17:29.528 24337-24337/org.mozilla.tv.firefox.debug I/cr_AWVDeploymentClient: disconnectRemote
2019-06-14 15:17:29.581 24337-24450/org.mozilla.tv.firefox.debug D/CRLSetManager: getInstance binder: android.os.BinderProxy@d75bd12
2019-06-14 15:17:29.620 24337-24337/org.mozilla.tv.firefox.debug I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
2019-06-14 15:17:29.721 24337-24436/org.mozilla.tv.firefox.debug W/OpenGLRenderer: Points are too far apart 4.000000
2019-06-14 15:17:29.773 24337-24367/org.mozilla.tv.firefox.debug I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=3de269e3-7890-4d44-967c-00b2452568d9, tags={ org.mozilla.tv.firefox.pocket.PocketVideoFetchWorker } ]
2019-06-14 15:17:30.141 24337-24337/org.mozilla.tv.firefox.debug W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 24337
2019-06-14 15:17:30.144 24337-24337/org.mozilla.tv.firefox.debug I/WebViewExtAmazon: Reducing mse video buffer to 90 MB
2019-06-14 15:17:30.145 24337-24337/org.mozilla.tv.firefox.debug I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
2019-06-14 15:17:30.270 24337-24342/org.mozilla.tv.firefox.debug I/art: Do partial code cache collection, code=50KB, data=60KB
2019-06-14 15:17:30.271 24337-24342/org.mozilla.tv.firefox.debug I/art: After code cache collection, code=50KB, data=60KB
2019-06-14 15:17:30.271 24337-24342/org.mozilla.tv.firefox.debug I/art: Increasing code cache capacity to 256KB
2019-06-14 15:17:30.307 24337-24337/org.mozilla.tv.firefox.debug W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 24337
2019-06-14 15:17:32.927 24337-24337/org.mozilla.tv.firefox.debug W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
2019-06-14 15:17:35.792 24337-24337/org.mozilla.tv.firefox.debug W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
2019-06-14 15:17:35.836 24337-24337/org.mozilla.tv.firefox.debug W/View: requestLayout() improperly called by org.mozilla.tv.firefox.FocusLossFrameLayout{c70dce0 VFE...CL. ......ID 24,0-411,279 #7f0900c9 app:id/home_tile} during layout: running second layout pass
2019-06-14 15:17:35.837 24337-24337/org.mozilla.tv.firefox.debug W/View: requestLayout() improperly called by org.mozilla.tv.firefox.FocusLossFrameLayout{49a7b99 VFE...CL. .F....ID 24,0-411,279 #7f0900c9 app:id/home_tile} during layout: running second layout pass
2019-06-14 15:17:35.837 24337-24337/org.mozilla.tv.firefox.debug W/View: requestLayout() improperly called by androidx.cardview.widget.CardView{8c56e5e V.E...... ......ID 0,0-387,216 #7f090053 app:id/channel_cardview} during layout: running second layout pass
2019-06-14 15:17:35.837 24337-24337/org.mozilla.tv.firefox.debug W/View: requestLayout() improperly called by androidx.cardview.widget.CardView{e64d23f V.E...... ......ID 0,0-387,216 #7f090053 app:id/channel_cardview} during layout: running second layout pass
2019-06-14 15:17:35.863 24337-24337/org.mozilla.tv.firefox.debug W/View: requestLayout() improperly called by org.mozilla.tv.firefox.FocusLossFrameLayout{49a7b99 VFE...CL. .F...... 114,0-501,279 #7f0900c9 app:id/home_tile} during second layout pass: posting in next frame
2019-06-14 15:17:37.627 24337-24337/org.mozilla.tv.firefox.debug W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
2019-06-14 15:17:37.665 24337-24337/org.mozilla.tv.firefox.debug D/AndroidRuntime: Shutting down VM
2019-06-14 15:17:37.677 24337-24337/org.mozilla.tv.firefox.debug D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
2019-06-14 15:17:37.830 24337-24337/org.mozilla.tv.firefox.debug W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
2019-06-14 15:17:37.830 24337-24337/org.mozilla.tv.firefox.debug W/System.err: SLF4J: Defaulting to no-operation MDCAdapter implementation.
2019-06-14 15:17:37.830 24337-24337/org.mozilla.tv.firefox.debug W/System.err: SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
2019-06-14 15:17:37.832 24337-24337/org.mozilla.tv.firefox.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.tv.firefox.debug, PID: 24337
    java.lang.IllegalArgumentException: parameter must be a descendant of this view
        at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:5459)
        at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:5388)
        at androidx.core.widget.NestedScrollView.isWithinDeltaOfScreen(NestedScrollView.java:1349)
        at androidx.core.widget.NestedScrollView.onSizeChanged(NestedScrollView.java:1788)
        at android.view.View.sizeChange(View.java:17764)
        at android.view.View.setFrame(View.java:17726)
        at android.view.View.layout(View.java:17634)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at androidx.core.widget.NestedScrollView.onLayout(NestedScrollView.java:1733)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:742)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2356)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2078)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6374)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:878)
        at android.view.Choreographer.doCallbacks(Choreographer.java:689)
        at android.view.Choreographer.doFrame(Choreographer.java:623)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:864)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method)
2019-06-14 15:17:37.833 24337-24337/org.mozilla.tv.firefox.debug E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
2019-06-14 15:17:37.862 24337-24337/org.mozilla.tv.firefox.debug I/Process: Sending signal. PID: 24337 SIG: 9
```

**Comment by mcomella** [comment]
I think the NestedScrollView (not sure if that's `<NestedScrollView>` or `BrowserNavigationOverlayScrollView`) is trying to calculate a size change using the currently focused descendant in layout – the last tile to be removed's `FocusLossFrameLayout` – but that view is already removed from the view hierarchy and we crash.

I'm not sure why the tile view is currently focused if it was removed from the view hierarchy – maybe it's a framework bug. I also don't know how removal is triggered.

**Comment by Baron-Severin** [comment]
I spent some time looking at differences between the pinned tiles channel (where this is not reproducible) and other channels (where it is).  We currently set pinned visibility to gone when it has no contents, but don't yet do that with other channels.  I notice that if I remove this visibility toggle, this crash becomes reproducible for pinned tiles.

So:
1) We have an easy fix here by adding visibility toggles to other channels.  This was already planned, so we should probably do it anyway.
2) This doesn't tell us what the root cause is, which could come back to bite us in the future.

**Comment by abodea** [comment]
Verified as fixed with the latest debug build, builded locally **`FF for Fire TV 3.11-LAT3(Build #59.0.3071.125)`** .
Please note that I modified the command from 
**``adb shell am start -n org.mozilla.tv.firefox/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments TvGuideChannels-2195:B``**
 to 
**`adb shell am start -n org.mozilla.tv.firefox.debug/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments TvGuideChannels-2195:B`** where I added **`.debug`** being the correct package name of the debug build.
I deleted all the tiles for at least 5 times and I had 0 crashes.
