### ISSUE TITLE
IllegalStateException: FragmentManager

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#248]
I wonder if this is because we're mixing the support library version of FragmentManager and the built-in version.

```
java.lang.RuntimeException
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3052)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3088)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1365)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5483)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.IllegalStateException
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2044)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2067)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:680)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:634)
    at org.mozilla.focus.activity.MainActivity.showBrowserScreenForCurrentSession(MainActivity.java:444)
    at org.mozilla.focus.activity.MainActivity.access$700(MainActivity.java:57)
    at org.mozilla.focus.activity.MainActivity$7.onValueChanged(MainActivity.java:248)
    at org.mozilla.focus.activity.MainActivity$7.onValueChanged(MainActivity.java:230)
    at org.mozilla.focus.architecture.NonNullObserver.onChanged(NonNullObserver.kt:14)
    at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:131)
    at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:143)
    at android.arch.lifecycle.LiveData.access$400(LiveData.java:63)
    at android.arch.lifecycle.LiveData$LifecycleBoundObserver.activeStateChanged(LiveData.java:395)
    at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:378)
    at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:353)
    at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:291)
    at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:331)
    at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
    at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
    at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
    at android.arch.lifecycle.ReportFragment.onResume(ReportFragment.java:88)
    at android.app.Fragment.performResume(Fragment.java:2096)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:928)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
    at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1879)
    at android.app.Activity.performResume(Activity.java:6140)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3036)
    ... 9 more
```

**Comment by bkmunar** [comment]
Oops referenced wrong issue
