### ISSUE TITLE
Startup crash: PatternSyntaxException: Syntax error in regexp pattern near index 4:

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2480]
## Steps to reproduce
- Launch firefox from upstream/master **on device**

### Expected behavior
App starts

### Actual behavior
app crashes

### Device information
* Fire TV device: Stick
* Latest affected Firefox version: up/master 202345441ebdd778066efd9dae92c66cf68eb9fc
* Earliest affected Firefox version: ?
* Turbo Mode: ?

Suspected regression: a-c upgrade in https://github.com/mozilla-mobile/firefox-tv/issues/2432

```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.tv.firefox.debug/org.mozilla.tv.firefox.MainActivity}: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 4:
    (?<major>[0-9]+)\.(?<minor>[0-9]+)(?:\.(?<patch>[0-9]+))?(?<metadata>[^0-9].*)?
        ^
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2473)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2541)
        at android.app.ActivityThread.access$800(ActivityThread.java:160)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5597)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 4:
    (?<major>[0-9]+)\.(?<minor>[0-9]+)(?:\.(?<patch>[0-9]+))?(?<metadata>[^0-9].*)?
        ^
        at java.util.regex.Pattern.compileImpl(Native Method)
        at java.util.regex.Pattern.compile(Pattern.java:411)
        at java.util.regex.Pattern.<init>(Pattern.java:394)
        at java.util.regex.Pattern.compile(Pattern.java:381)
        at kotlin.text.Regex.<init>(Regex.kt:89)
        at mozilla.components.concept.engine.utils.EngineVersion$Companion.parse(EngineVersion.kt:71)
        at mozilla.components.browser.engine.system.SystemEngine.getVersion(SystemEngine.kt:77)
        at org.mozilla.tv.firefox.MainActivity.onCreate(MainActivity.kt:113)
        at android.app.Activity.performCreate(Activity.java:6010)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
```

**Comment by pocmo** [comment]
Fixed in AC 2.0.0 (released earlier this week). Affects Android 5.0/5.1 devices.
