### ISSUE TITLE
[Amazon] Parcel NPE

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#251]
```
java.lang.NullPointerException
    at android.os.Parcel.readException(Parcel.java:1572)
    at android.os.Parcel.readException(Parcel.java:1519)
    at com.amazon.android.service.hdmi.IAmazonHdmiServiceManager$Stub$Proxy.getCurrentMode(IAmazonHdmiServiceManager.java:432)
    at com.amazon.android.service.hdmi.AmazonDisplayCallback.onGetMode(AmazonDisplayCallback.java:93)
    at android.view.VendorDisplayCallback.callOnGetMode(VendorDisplayCallback.java:120)
    at android.view.Display.getMode(Display.java:957)
    at org.chromium.ui.VSyncMonitor$AwvDisplayListener.onDisplayChanged(VSyncMonitor.java:171)
    at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:476)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5483)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by Sdaswani** [comment]
More info from Amazon:

> This issue is not customer facing. The exception is thrown while the app is in the background or when the TV is turned off. When the customer switches to the app, it will just take longer to load. This issue only affects our 1st generation devices. We are working on a fix for a future OS update.

**Comment by athomasmoz** [comment]
@liuche can I close this as won't fix?
