### ISSUE TITLE
[Amazon] AmazonMediaPlayerBridge NPE

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#252]
```
java.lang.NullPointerException
    at org.chromium.amazon_webview.browser.media.AmazonMediaPlayerBridge.handleTextTrack(AmazonMediaPlayerBridge.java:582)
    at org.chromium.amazon_webview.browser.media.AmazonMediaPlayerBridge.onPlayerStateChange$3a5fd2cb(AmazonMediaPlayerBridge.java:635)
    at com.amazon.mediaplayer.exoplayer.ExoPlayerStateMachineImpl$1.run(ExoPlayerStateMachineImpl.java:1741)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5483)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by Sdaswani** [comment]
In the past month we only saw this issues 528 times. Not a hugely impactful crash.

**Comment by athomasmoz** [comment]
@liuche can I close this as won't fix?
