### ISSUE TITLE
[Amazon] AwContents OOM

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#253]
```
java.lang.OutOfMemoryError
    at org.chromium.android_webview.AwContents$AwComponentCallbacks.onTrimMemory(AwContents.java:717)
    at android.app.Application.onTrimMemory(Application.java:128)
    at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4368)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5483)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by Sdaswani** [comment]
From Amazon: As for OOM issue (https://github.com/mozilla-mobile/firefox-tv/issues/253), we will have to investigate more, where the memory is being consumed.
On your end can you please see, how much memory is being used by the Firefox app while navigating across different sites?

**Comment by athomasmoz** [comment]
@liuche can I close this as won't fix?
