### ISSUE TITLE
FFTV crashes when scrolling fast to the right in pocket section 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2727]
## Steps to reproduce
1. Launch FF.
2. Reach the menu overview.
3. Select Pocket section.
4. Tap on the right button from the remote and hold until reaching the last pocket tile.
### Expected behavior
The last pocket tile is displayed and selected correctly.
### Actual behavior
FFTV crashes when scrolling fast to the right.
### Device information
* Fire TV device: Fire TV 4k Stick and pendant. 
* Latest affected Firefox version: **`Firefox TV 4.3-LAT2`**
* Earliest affected Firefox version: **`Firefox TV 4.0-LAT1`** - but I believe the issue is way older or related to pocket content.
* Turbo Mode: **`On and OFF`**
### Notes
Please note that I remember trying this almost every time when testing with each tile section but I never got a crash.
Maybe is something going on with the **Pocket** content. I was able to reproduce the issue on very old **LATS** and its not very clear if is the content of the pocket(Note that the same sites are displayed for all the installed **LATS**).
I also had on an **2nd Gen Stick** the **LAT1 4.3** with way less content on the pocket section(less sites) and it didn't crashed.
Also, note that this issue occurs only for the Pocket section, everything else is working as expected.
[crashlog.txt](https://github.com/mozilla-mobile/firefox-tv/files/3530172/crashlog.txt)

**Comment by abodea** [comment]
```css
--------- beginning of crash
2019-08-22 15:40:30.518 29167-29167/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.tv.firefox, PID: 29167
    java.lang.IllegalArgumentException: parameter must be a descendant of this view
        at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:5459)
        at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:5388)
        at androidx.core.widget.NestedScrollView.isWithinDeltaOfScreen(NestedScrollView.java:1349)
        at androidx.core.widget.NestedScrollView.onSizeChanged(NestedScrollView.java:1788)
        at android.view.View.sizeChange(View.java:17767)
        at android.view.View.setFrame(View.java:17729)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at androidx.core.widget.NestedScrollView.onLayout(NestedScrollView.java:1733)
        at android.view.View.layout(View.java:17640)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17640)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17640)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17640)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17640)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17640)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17640)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17640)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:742)
        at android.view.View.layout(View.java:17640)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2356)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2078)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6374)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:878)
        at android.view.Choreographer.doCallbacks(Choreographer.java:689)
        at android.view.Choreographer.doFrame(Choreographer.java:623)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:864)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method)
2019-08-22 15:40:30.519 29167-29167/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)```

**Comment by abodea** [comment]
Also, I noticed this when scrolling in pocket.
```css
2019-08-22 15:51:28.522 762-912/? E/bt_btif: bta_hh_le_input_rpt_notify uuid=0x2a4d srv_handle=79 is_bl_svc_primary=1
2019-08-22 15:51:30.262 762-912/? E/bt_btif: bta_hh_le_input_rpt_notify uuid=0x2a4d srv_handle=79 is_bl_svc_primary=1
2019-08-22 15:51:30.382 762-912/? E/bt_btif: bta_hh_le_input_rpt_notify uuid=0x2a4d srv_handle=79 is_bl_svc_primary=1
2019-08-22 15:51:32.042 762-912/? E/bt_btif: bta_hh_le_input_rpt_notify uuid=0x2a4d srv_handle=79 is_bl_svc_primary=1
2019-08-22 15:51:32.082 762-912/? E/bt_btif: bta_hh_le_input_rpt_notify uuid=0x2a4d srv_handle=79 is_bl_svc_primary=1
2019-08-22 15:51:33.342 762-912/? E/bt_btif: bta_hh_le_input_rpt_notify uuid=0x2a4d srv_handle=79 is_bl_svc_primary=1
2019-08-22 15:51:33.443 3055-30924/? E/DiscoveryService: SsdpNanoHTTPD - Error in Service loop - Read timed out;
2019-08-22 15:51:33.482 762-912/? E/bt_btif: bta_hh_le_input_rpt_notify uuid=0x2a4d srv_handle=79 is_bl_svc_primary=1
```

**Comment by Baron-Severin** [comment]
A few investigation notes:

A similar issue was fixed in #2313. 

Pocket has more tiles than other channels (Pocket: 20, pinned: 10), but this does __not__ appear to be related.  This was still not reproducible in the pinned channel after tripling its item count.

This crash is only reproducible when scrolling right.  Scrolling left from the end consistently works as expected.

**Comment by Baron-Severin** [comment]
If all title and subtitle text is removed and replaced with one line strings (e.g., I replaced the text with each tile index for debugging purposes), this bug is no longer reproducible.

**Comment by Baron-Severin** [comment]
(All counting in this comment start with 0-index.  It also appears to be related to the exact content, and will probably be different the next time the videos change)

If I start on the 0th, 1st, or 2nd tile and then hold down the right dpad, it will consistently crash when the 9th element is focused.  

If I start on index 4-8, it will consistently crash when 15 is focused.

If I start on 9+, it will not crash.

Hypothesis:
- Must be full speed scrolling to crash (hence why starting on 3 won't crash on 9)
- Something about the size of 9 and 15 (or possibly 8 & 14) is causing a crash (the fact that [shortening the included text fixes the crash](suggests to me that size has something to do with this))

**Comment by Baron-Severin** [comment]
This crash occurs when:
- The user scrolls quickly
- The list contains a tile with a title (not description) of 2 or more lines
- This 2 line title is neither the 0th nor last tile in the channel
- The tile with a 2 line title enters or exits the screen, forcing the Pinned Tiles channel to move up or down

I have no idea why this doesn't happen when scrolling in reverse.

**Comment by Baron-Severin** [comment]
@brampitoyo the easiest fix for this bug would be to restrict Pocket author strings to 1 line, and ellipsize past that.  Most are already one line, and this would also fix the issue where the Pinned Tiles channel moves around awkwardly during scrolling.  We're already ellipsizing the descriptions.  Does this sound acceptable to you?

(awkward channel movement video taken from master)
![resizing-channel](https://user-images.githubusercontent.com/13170306/63548624-7620eb80-c4e3-11e9-9bc7-03ef05805089.gif)

**Comment by abodea** [comment]
@Baron-Severin I builded both versions `59.xx` and `70.xx` but in both builds I had only 5 pocket sites. Its my first time when I managed to make it work and build with a pocket key.
Is there something more that I need to do in order to have more websites in Pocket section?
Also, with those 5 websites from pocket I couldn't reproduce the issue.

**Comment by Baron-Severin** [comment]
@abodea I'm not super familiar with our Pocket setup, but my understanding is that on a fresh install it will always use those 5.  It then makes a network request sometime in the early morning (local time), then displays those the next time the app is used.  I don't think there's an easy way for you to bypass that, although we should consider building one in.

For what it's worth, I tested this one myself (it required some code changes) and I'm confident that it works as expected.  Maybe we should just skip QA on this one, especially as it was originally marked as a low priority bug anyway.

**Comment by brampitoyo** [comment]
@Baron-Severin wrote:

> @brampitoyo the easiest fix for this bug would be to restrict Pocket author strings to 1 line, and ellipsize past that. Most are already one line, and this would also fix the issue where the Pinned Tiles channel moves around awkwardly during scrolling. We're already ellipsizing the descriptions. Does this sound acceptable to you?

I agree with you that we should restrict the Pocket author string to only occupy one line. Let’s do that.
