### ISSUE TITLE
[FxA] Crash after Sign-In 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-tv#2767]
## Steps to reproduce
1. Sign in to FFTV 

### Expected behavior
User is successfully signed in 

### Actual behavior
Crash

### Device information
* Fire TV device: **FireTV 4k pendant**
* Latest affected Firefox version: **Firefox for FireTV 4.4-LAT1**
* Earliest affected Firefox version: **Firefox for FireTV 4.4-LAT1**
* Turbo Mode: OK

### Notes
Similar with #2759 
Crash log
```
   --------- beginning of crash
2019-08-29 16:18:04.339 25193-25302/? E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
    Process: org.mozilla.tv.firefox, PID: 25193
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at io.reactivex.internal.operators.observable.ObservableHide$HideDisposable.onNext(ObservableHide.java:67)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:564)
        at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:268)
        at org.mozilla.tv.firefox.fxa.FxaRepo$FirefoxAccountObserver.onAuthenticated(FxaRepo.kt:120)
        at mozilla.components.service.fxa.manager.FxaAccountManager$postAuthenticated$2.invoke(FxaAccountManager.kt:755)
        at mozilla.components.service.fxa.manager.FxaAccountManager$postAuthenticated$2.invoke(FxaAccountManager.kt:101)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:131)
        at mozilla.components.service.fxa.manager.FxaAccountManager.notifyObservers(FxaAccountManager.kt)
        at mozilla.components.service.fxa.manager.FxaAccountManager.postAuthenticated(FxaAccountManager.kt:755)
        at mozilla.components.service.fxa.manager.FxaAccountManager.stateActions(FxaAccountManager.kt:570)
        at mozilla.components.service.fxa.manager.FxaAccountManager$stateActions$1.invokeSuspend(FxaAccountManager.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6928)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1085)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5205)
        at android.view.View.invalidateInternal(View.java:13659)
        at android.view.View.invalidate(View.java:13623)
        at android.view.View.invalidate(View.java:13607)
        at android.widget.ImageView.invalidateDrawable(ImageView.java:255)
        at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:435)
        at android.graphics.drawable.Drawable.setVisible(Drawable.java:819)
        at android.widget.ImageView.updateDrawable(ImageView.java:960)
        at android.widget.ImageView.setImageDrawable(ImageView.java:526)
        at androidx.appcompat.widget.AppCompatImageButton.setImageDrawable(AppCompatImageButton.java:90)
        at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:90)
        at androidx.appcompat.widget.AppCompatImageButton.setImageResource(AppCompatImageButton.java:85)
        at org.mozilla.tv.firefox.navigationoverlay.NavigationOverlayFragment$observeAccountState$1.accept(NavigationOverlayFragment.kt:269)
        at org.mozilla.tv.firefox.navigationoverlay.NavigationOverlayFragment$observeAccountState$1.accept(NavigationOverlayFragment.kt:87)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableHide$HideDisposable.onNext(ObservableHide.java:67) 
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246) 
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569) 
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:564) 
        at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:268) 
        at org.mozilla.tv.firefox.fxa.FxaRepo$FirefoxAccountObserver.onAuthenticated(FxaRepo.kt:120) 
        at mozilla.components.service.fxa.manager.FxaAccountManager$postAuthenticated$2.invoke(FxaAccountManager.kt:755) 
        at mozilla.components.service.fxa.manager.FxaAccountManager$postAuthenticated$2.invoke(FxaAccountManager.kt:101) 
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:131) 
        at mozilla.components.service.fxa.manager.FxaAccountManager.notifyObservers(FxaAccountManager.kt) 
        at mozilla.components.service.fxa.manager.FxaAccountManager.postAuthenticated(FxaAccountManager.kt:755) 
        at mozilla.components.service.fxa.manager.FxaAccountManager.stateActions(FxaAccountManager.kt:570) 
        at mozilla.components.service.fxa.manager.FxaAccountManager$stateActions$1.invokeSuspend(FxaAccountManager.kt) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
2019-08-29 16:18:04.372 3469-4621/? W/ActivityManager:   Force finishing activity org.mozilla.tv.firefox/.MainActivity
```

► Video
![20190829_160235_2](https://user-images.githubusercontent.com/51314259/63949585-5493a700-ca83-11e9-81cb-97d8252ee984.gif)

**Comment by mcomella** [comment]
Suspected dupe #2759.

**Comment by AndiAJ** [comment]
Hi, just as an FYI, this is reproducible after logging in through the Account creation flow.
For a short period of time a red snackbar notification is displayed stating "Invalid token"
