### ISSUE TITLE
IllegalStateException (no crash): beginAuthenticationSync returned null loginUri

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2946]
via:
- https://sentry.prod.mozaws.net/operations/firefox-tv/issues/6374550/
- https://sentry.prod.mozaws.net/operations/firefox-tv/issues/6354431/

## Steps to reproduce
Unknown. afaik, `beginAuthenticationSync` may return null when:
- Called `beginAuthenticationSync` was called but before we load the URL it returned (do we need to debounce button clicks?)
- The FxA lib encounters an error such as being unable to connect to the network

### Expected behavior
Does not return null.

### Actual behavior
Returns null, no crash: **we don't know for sure what the consequence of this is** or if it's disruptive. Here's some possibilities:
- Worst case? The user would go through the entire sign in flow **but sign in would fail** (we fixed an issue like this)
- Clicking the sign in button does nothing
- Nothing bad happens

Currently, this happens for ~0.87%, or 1/125, of clicks on sign in: this seems significant for an already difficult user work flow.

### Device information
* Fire TV device: ?
* Latest affected Firefox version: v4.5
* Earliest affected Firefox version: ?
* Turbo Mode: ?

Stack trace:
```
java.lang.IllegalStateException: beginAuthenticationAsync returned null loginUri
    at org.mozilla.tv.firefox.fxa.FxaLoginUseCase$beginLogin$1.invokeSuspend(FxaLoginUseCase.kt:60)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

**Comment by mcomella** [comment]
> Called beginAuthenticationSync was called but before we load the URL it returned (do we need to debounce button clicks?)

I tried clicking both the preboarding and the nav overlay button quickly but was unable to reproduce.

**Comment by mcomella** [comment]
I checked the telemetry for Nov. 17th and our failure rate is similar to when I filed this bug: users see this error ~0.83% of the time.

**Comment by mcomella** [comment]
I spoke with Grisha who believes this might be attributable to network errors.

The Sentry reports have an "online" field (see caveats below) and in the first 200 entries, 69.5% of users have "online = true".

### Next steps
- Do a static analysis of the code to look for bugs.
- Compare our failure rate to the network failure rates on desktop.

If the failure rate is significantly higher than desktop, we should start recording the exception reason in the FxA lib (i.e. FxaNetworkException, FxaUnauthorizedException, FxaUnspecifiedException) and report it to Sentry.

### Additional considerations
On error, we currently don't do display anything to the user: we should consider changing that.

### Online caveats
1. activeNetworkInfo.isConnected() (which is called to collect that field) might be true when the user is connected to wifi but not the internet
2. that field may take a little time to update (e.g. to try to be robust from errors)

**Comment by mcomella** [comment]
Interesting note from Grisha regarding the severity of this issue:

> so you'll be reducing your login success rate by at most ~1%, right? if top of the funnel is reduced by 0.87% due to errors

**Comment by mcomella** [comment]
After consulting with the FxA team and athomas, we decided that the ~0.8% error rate could be indicative of network errors and isn't worth investigating in the short term.

If we were to pursue next steps, we could:
- Send a data science request to compare our network error percentage to desktop’s in a similar case. If they’re different…
- Add additional logging in a-c (which will require an uplift or for us to upgrade a-c) to determine the error type. Grisha might end up doing this anyway in the future (and if it’s a priority for us, we can request it)
- Do more aggressively static code analysis

In the mean time, unassigning and deprioritizing.
