### ISSUE TITLE
Startup getText crash

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2971]
Sentry issues: 
https://sentry.prod.mozaws.net/operations/firefox-tv/issues/6742145/
https://sentry.prod.mozaws.net/operations/firefox-tv/issues/6742146/

### Notes
- This has only happened to one person, but it happened twice in 2 (?) minutes
- Based on timestamps, it looks like it's happening on startup
- The crash is an invalid call to `getText`, but it's unclear exactly where it's happening

## Steps to reproduce
- ???

### Device information
* Fire TV device: AFTM
* Latest affected Firefox version: v4.6
* Earliest affected Firefox version: v4.6
* Turbo Mode: ?

**Comment by Baron-Severin** [comment]
Investigation notes
- This has only happened to one person, but it happened twice in 2 (?) minutes
- Based on timestamps, it looks like it's happening on startup
- The crash is an invalid call to `getText`, but it's unclear exactly where it's happening
- I diffed `releases/v4.6` and `releases/v4.5` and grepped for `R.string`, and [this was the only added usage](https://github.com/mozilla-mobile/firefox-tv/blob/b51a9459d2d983f387f57a79db12b5766b8d70aa/app/src/main/java/org/mozilla/tv/firefox/settings/SettingsFragment.kt#L180), but it looks valid, and also doesn't seem like it would be displayed on startup.

**Comment by mcomella** [comment]
Random thoughts:
* It looks like Chromium is calling `getTextInputName` (what does that do?) without any of our code running in the current trace (so on user touch?).
* There are similar crash traces for `NotFoundException`s related to being unable to fetch a resource. In this case, an image file: https://sentry.prod.mozaws.net/operations/firefox-tv/issues/6610720/
* This is spread across multiple Sentry issues because the String ID changes (could we track down those String IDs to figure out the context?)
* This only affects 7 users currently and, given there are separate issues, there may be some overlap in that number: maybe this is insignificant.

**Comment by mcomella** [comment]
It's possible our hack fix for switching tabs to enters is causing a race condition in the WebView which is causing the crash. Since this hack affects a limited subset of pages, that could be why we're seeing such low user counts.

**Comment by mcomella** [comment]
I noticed the stack traces have, `updateBuellerCustomOptions`. This is an Amazon (or custom ROM) method because [it doesn't appear in androidxref](http://androidxref.com/9.0.0_r3/search?q=updateBuellerCustomOptions&defs=&refs=&path=&hist=&project=frameworks). I searched "fire tv bueller" and it appears this is a codename for the first Fire TV (via [aftvnews](http://www.aftvnews.com/amazons-next-generation-fire-tv-is-codenamed-sloane-new-fire-tv-stick-is-unlikely/)). We only have crashes on AFTS (stick gen 1) & AFTM (TV gen 2).

**Comment by mcomella** [comment]
The build code of the APK for the crashing users is all the same but we're unable to verify it comes from our actual APK because we're unable to get the final APK from the Amazon store because it's undergoing staged rollout (I tried uninstall & reinstall 6+ times and was unable to get it).

**Comment by mcomella** [comment]
We suspected there might be a startup crash with accessibility enabled – because we may not have tested that – but we were unable to reproduce (to be fair, we don't have the devices the issues are on). As such, we're okay increasing the staged rollout and seeing if it becomes a problem.

**Comment by mcomella** [comment]
There have been 887 crashes for 212 users since this issue was first seen 7 days ago (starting roll out) and since we finished rollout 5 days ago. It's at most ~200 events per day (on weekends).

This doesn't seem _too_ significant but it might be something to look out for.

Given the crypticness of the error, however, I wonder if this was an issue with:
1) How the APK was built
2) How the APK was signed and potentially modified by the Amazon app store
3) OS upgrades that occurred around the same time as our release

So maybe it'll go away for the next release.

**Comment by mikespub** [comment]
FYI I'm getting the same error on a Fire (2015) device with an app using the Android WebView after submission to the Amazon App Store.

Other Fire & Android devices don't report that issue, and I don't believe this has anything to do with your code.

```
android.content.res.Resources$NotFoundException: String resource ID #0x1405003d
	at android.content.res.Resources.getText(Resources.java:306)
	at android.content.res.Resources.getString(Resources.java:392)
	at android.content.Context.getString(Context.java:383)
	at org.chromium.content.browser.input.ImeAdapter.getTextInputName(ImeAdapter.java:264)
	at org.chromium.content.browser.input.AdapterInputConnection.updateBuellerCustomOptions(AdapterInputConnection.java:693)
	at org.chromium.content.browser.input.AdapterInputConnection.<init>(AdapterInputConnection.java:159)
	at org.chromium.content.browser.input.ImeAdapter$AdapterInputConnectionFactory.get(ImeAdapter.java:209)
	at org.chromium.content.browser.ContentViewCore.onCreateInputConnection(ContentViewCore.java:1496)
	at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onCreateInputConnection(AwContents.java:2456)
	at org.chromium.android_webview.AwContents.onCreateInputConnection(AwContents.java:1548)
	at com.android.webview.chromium.WebViewChromium.onCreateInputConnection(WebViewChromium.java:1713)
	at android.webkit.WebView.onCreateInputConnection(WebView.java:2417)
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1181)
	at android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1433)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3333)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5462)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```
