### ISSUE TITLE
1.1 APK downloaded from Google drive crashes

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#366]
Below is the crash stack, and it seems to happen to both me and @bbinto 

D/AndroidRuntime( 5641): Shutting down VM
E/AndroidRuntime( 5641): FATAL EXCEPTION: main
E/AndroidRuntime( 5641): Process: org.mozilla.tv.firefox.debug, PID: 5641
E/AndroidRuntime( 5641): java.lang.RuntimeException: Unable to instantiate application org.mozilla.focus.FocusApplication: java.lang.ClassNotFoundException: Didn't find class "org.mozilla.focus.FocusApplication" on path: DexPathList[[zip file "/data/app/org.mozilla.tv.firefox.debug-1/base.apk", zip file "/system/priv-app/MetricsApi/MetricsApi.apk", zip file "/system/priv-app/com.amazon.dp.logger/com.amazon.dp.logger.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 5641): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:596)
E/AndroidRuntime( 5641): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4747)
E/AndroidRuntime( 5641): 	at android.app.ActivityThread.access$1500(ActivityThread.java:160)
E/AndroidRuntime( 5641): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
E/AndroidRuntime( 5641): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5641): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5641): 	at android.app.ActivityThread.main(ActivityThread.java:5483)
E/AndroidRuntime( 5641): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5641): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5641): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
E/AndroidRuntime( 5641): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/AndroidRuntime( 5641): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.mozilla.focus.FocusApplication" on path: DexPathList[[zip file "/data/app/org.mozilla.tv.firefox.debug-1/base.apk", zip file "/system/priv-app/MetricsApi/MetricsApi.apk", zip file "/system/priv-app/com.amazon.dp.logger/com.amazon.dp.logger.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 5641): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 5641): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 5641): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 5641): 	at android.app.Instrumentation.newApplication(Instrumentation.java:981)
E/AndroidRuntime( 5641): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:590)
E/AndroidRuntime( 5641): 	... 10 more
E/AndroidRuntime( 5641): 	Suppressed: java.lang.ClassNotFoundException: org.mozilla.focus.FocusApplication
E/AndroidRuntime( 5641): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 5641): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 5641): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 5641): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 5641): 		... 13 more
E/AndroidRuntime( 5641): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
I/AndroidRuntime( 5641): To Report FATAL to activityManagerService
I/ActivityManager(  970): handleApplicationCrash
I/AmazonAppstore.DumbMetricsDelegate( 3825): About to submit AppLaunchFromInternal
I/AivConnector( 1444): Calling cleanup on AmazonInstantVideo
I/ImageCache( 1444): handleTrimMemory - evicting cached images - memorySaved: 0 bytes
I/ImageCache( 1444): handleTrimMemory - scheduled frozen image releases - numberOfImages: 25, memory: 22 MB
W/ActivityManager(  970):   Force finishing activity 1 org.mozilla.tv.firefox.debug/org.mozilla.focus.activity.MainActivity
I/ImageCache( 1444): scheduling secondary trim
I/ActivityManager(  970): addErrorToDropBox inserted hashcode=62675c9b32e53d755dc6ef7e9a08163faebca52f for eventType crash.

**Comment by npark-mozilla** [comment]
fixed now
