### ISSUE TITLE
Fix App Exit

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#460]
Issue 1               : App exits after performing mic search during the video playback  and pressing back button
Issue reproducible    : All compatible Fire TV devices.            
Reproducibility Rate  :  5/5
Issue reproducible in live: NO
 
Steps to reproduce
1. Install and launch the app
2. Select YouTube
3. Scroll Down and select any of the videos
4. While the video is playing performing Mic search and invoke any of the apps like Calm radio
5. Press back button using Remote/controller
 
Actual Result: App exits to device home screen
Expected Result: App should resume the video
 
Attachment:FireFox_Youtube_EXIT_2015.txt
Video Link:https://www.amazon.com/clouddrive/share/JkDBex6SLuHlSYnwziyGWodydZVhpX77DdJ...

**Comment by boek** [comment]
Got a stack trace 👍 
```
02-02 17:35:47.064 16208-16208/org.mozilla.tv.firefox.debug A/cr_Cloud9JNICrash: java.lang.RuntimeException: Attempting to register invalid Surface.
                                                                                     at org.chromium.content.browser.ChildProcessLauncher.registerViewSurface(ChildProcessLauncher.java:518)
                                                                                     at org.chromium.components.external_video_surface.ExternalVideoSurfaceContainer.nativeSurfaceCreated(Native Method)
                                                                                     at org.chromium.components.external_video_surface.ExternalVideoSurfaceContainer.createSurfaceView(ExternalVideoSurfaceContainer.java:236)
                                                                                     at org.chromium.components.external_video_surface.ExternalVideoSurfaceContainer.requestExternalVideoSurface(ExternalVideoSurfaceContainer.java:166)
                                                                                     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                                     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5483)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-02 17:35:47.120 16208-16208/org.mozilla.tv.firefox.debug A/chromium: [FATAL:jni_android.cc(245)] Please include Java exception stack in crash report
                                                                        #00 0xa4b5a39f /system/lib/libwebviewextchromium.so+0x002cd39f
                                                                        #01 0xa4b461bd /system/lib/libwebviewextchromium.so+0x002b91bd
                                                                        #02 0xa5bc5843 /system/lib/libwebviewextchromium.so+0x01338843
                                                                        #03 0xa5bbd2b7 /system/lib/libwebviewextchromium.so+0x013302b7
                                                                        #04 0xa5bbd2d7 /system/lib/libwebviewextchromium.so+0x013302d7
                                                                        #05 0xa33bb855 /data/dalvik-cache/arm/system@app@AmazonWebView@AmazonWebView.apk@classes.dex+0x002eb855
02-02 17:35:47.421 16208-16208/org.mozilla.tv.firefox.debug W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
02-02 17:35:47.422 16208-16208/org.mozilla.tv.firefox.debug W/google-breakpad: Chrome build fingerprint:
02-02 17:35:47.422 16208-16208/org.mozilla.tv.firefox.debug W/google-breakpad: 1.1.1
02-02 17:35:47.422 16208-16208/org.mozilla.tv.firefox.debug W/google-breakpad: 11
02-02 17:35:47.422 16208-16208/org.mozilla.tv.firefox.debug W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
02-02 17:35:47.422 16208-16208/org.mozilla.tv.firefox.debug A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 16208 (v.firefox.debug)
```

**Comment by mcomella** [comment]
@boek Some things to look at:
- Do we have the same problems with a desktop user agent? You can spoof it [here](https://github.com/mozilla-mobile/firefox-tv/blob/8c3cdf2116a4dd77fe60a5f81ebe909e0766128e/app/src/amazonWebview/java/org/mozilla/focus/browser/UserAgent.kt#L56)
- The fullscreen callbacks are [here](https://github.com/mozilla-mobile/firefox-tv/blob/8c3cdf2116a4dd77fe60a5f81ebe909e0766128e/app/src/amazonWebview/java/org/mozilla/focus/webview/FirefoxAmazonWebView.kt#L129) – maybe we're not exiting fullscreen before leaving the app and that's causing the crash?
    - Existing code is a little confusing: IWebView is passing it to the implementation and back again. fwiw, I always thought [we shouldn't call `onCustomViewHidden` when we leave](https://github.com/mozilla-mobile/firefox-tv/blob/8c3cdf2116a4dd77fe60a5f81ebe909e0766128e/app/src/amazonWebview/java/org/mozilla/focus/webview/FirefoxAmazonWebView.kt#L132) (to me, it looks like that is meant to force the app to close the view, rather than for us to call when the website closes the view) – maybe comment that out and see it it still happens

**Comment by boek** [comment]
So after some further investigation it looks like the AmazonWebView is cleaning up the surface that video is playing on when the application is backgrounded causing the application to crash when it attempts to bring the video back when we come back to Firefox. Thats where the limit of the code thats available to me and my Android skills.

The quick fix is to just make sure we close the full screen video player when backgrounding the application.
