### ISSUE TITLE
Crash in AmazonWebkitFactories

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#492]
This is a crash on the LiveTest 1.2 version - app crashes on startup.

Building and installing from source works for most people.

```
02-15 16:23:02.863 21774-21774/? W/com.amazon.android.webkit.AmazonWebKitFactories: Create WebKitFactoryByName failed: com.amazon.android.webkit.embedded.EmbeddedWebKitFactory
02-15 16:23:02.863 21774-21774/? W/com.amazon.android.webkit.AmazonWebKitFactories: Create WebKitFactoryByName failed: com.amazon.android.webkit.android.AndroidWebKitFactory
02-15 16:23:02.864 21774-21774/? D/AndroidRuntime: Shutting down VM
02-15 14:20:29.767 7097-7097/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.mozilla.tv.firefox, PID: 7097
java.lang.ExceptionInInitializerError
    at com.amazon.android.webkit.AmazonWebKitFactories.getDefaultFactory(AmazonWebKitFactories.java:132)
    at org.mozilla.focus.activity.MainActivity.initAmazonFactory(MainActivity.java:221)
    at org.mozilla.focus.activity.MainActivity.onCreateMainActivity(MainActivity.java:72)
    at org.mozilla.focus.activity.MainActivity.onCreate(MainActivity.java)
    at android.app.Activity.performCreate(Activity.java:6010)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435)
    at android.app.ActivityThread.access$800(ActivityThread.java:160)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5483)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
 Caused by: java.lang.RuntimeException: Unable to initialize webkit factory
    at com.amazon.android.webkit.AmazonWebKitFactories$Implementation.<clinit>(AmazonWebKitFactories.java:72)
    at com.amazon.android.webkit.AmazonWebKitFactories.getDefaultFactory(AmazonWebKitFactories.java:132) 
    at org.mozilla.focus.activity.MainActivity.initAmazonFactory(MainActivity.java:221) 
    at org.mozilla.focus.activity.MainActivity.onCreateMainActivity(MainActivity.java:72) 
    at org.mozilla.focus.activity.MainActivity.onCreate(MainActivity.java) 
    at android.app.Activity.performCreate(Activity.java:6010) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435) 
    at android.app.ActivityThread.access$800(ActivityThread.java:160) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5483) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

**Comment by Sdaswani** [comment]
Happy we LATed, better fix this now rather than closer to release. Thanks for looking into it @liuche .

**Comment by liuche** [comment]
@bkmunar since you were doing some of the Proguard work, I think this is fallout from not having tested the release build after we enabled proguard. I learned that you can look at `<firefox-tv>/app/build/outputs/mapping/amazonWebview/release/usage.txt` to see what is being removed.

@Sdaswani this is what getting a proguard config from the Amazon webview team would have helped us avoid.

---
Basically, AmazonWebKitFactories needs to instantiate two factories, and references them by string names, so Proguard doesn't know they're necessary (I assume).
Added these two files to be kept by proguard.

The relevant errors in the log are:
```
02-15 16:23:02.863 21774-21774/? W/com.amazon.android.webkit.AmazonWebKitFactories: Create WebKitFactoryByName failed: com.amazon.android.webkit.embedded.EmbeddedWebKitFactory
02-15 16:23:02.863 21774-21774/? W/com.amazon.android.webkit.AmazonWebKitFactories: Create WebKitFactoryByName failed: com.amazon.android.webkit.android.AndroidWebKitFactory
```

The decompiled bytecode version where this gets called:
```
private static boolean createWebKitFactoryByName(String factory) {
    try {
        FACTORY = (AmazonWebKitFactory)Class.forName(factory).newInstance();
        Log.i(AmazonWebKitFactories.TAG, "Successfully create WebKitFactory by name: " + factory);
        return true;
    } catch (Exception var2) {
        Log.w(AmazonWebKitFactories.TAG, "Create WebKitFactoryByName failed: " + factory);
        return false;
    }
}

static {
    String factory = null;

    try {
        factory = AmazonWebKitFactories.getExternalFactoryName();
        if(factory == null || factory.length() == 0) {
            factory = AmazonWebKitFactories.defaultFactory;
        }

        if(factory == null || factory.length() == 0 || !createWebKitFactoryByName(factory)) {
            String[] factories = new String[]{"com.amazon.android.webkit.embedded.EmbeddedWebKitFactory", "com.amazon.android.webkit.android.AndroidWebKitFactory"};
            String[] arr$ = factories;
            int len$ = factories.length;

            for(int i$ = 0; i$ < len$; ++i$) {
                String s = arr$[i$];
                if(createWebKitFactoryByName(s)) {
                    factory = s;
                    break;
                }
            }
        }
    } catch (Exception var6) {
        throw new RuntimeException("Unable to initialize webkit factory", var6);
    }

    if(FACTORY == null) {
        throw new RuntimeException("Unable to initialize webkit factory");
} 
```

**Comment by Sdaswani** [comment]
Sorry @liuche I asked for a recommended proguard config but they said there wasn’t one.

**Comment by liuche** [comment]
@Sdaswani I wonder if we can tell them, "well clearly there's a crash and here's the code that's doing it" and see if they have other suggestions? though maybe they're just suggesting that we don't proguard at all.

**Comment by liuche** [comment]
For QA, this is to test that on signed release (not beta or debug) builds (either by self-signing or through live-test) that we're not getting anymore crashes due to our proguarding.

**Comment by Sdaswani** [comment]
@liuche I'm fine with telling them about our experience to help out future users, but given they never recommended a proguard configuration, I don't feel comfortable pointing at their code as the source of any issues. Thanks for tracking this down so quickly!
