### ISSUE TITLE
[monkey] Crash: java.lang.IllegalStateException: Expected session to be started before session end is called

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#719]
This might actually be a problem in the Telemetry library. This is a low-volume crash that happens in the wild (count is 7 days):

![image](https://user-images.githubusercontent.com/759372/37799781-ff0e690c-2ddd-11e8-8e6e-faf3d6b9d9ec.png)

I get this on device and in the emulator. It seems to repro often with monkey testing.

```
// CRASH: org.mozilla.tv.firefox.debug (pid 7869)
// Short Msg: java.lang.IllegalStateException
// Long Msg: java.lang.IllegalStateException: Expected session to be started before session end is called
// Build Label: Amazon/needle:6.0/NS6212/927/N:user/amz-p,release-keys
// Build Changelist: 0000033791876
// Build Time: 1516321378000
// java.lang.IllegalStateException: Expected session to be started before session end is called
//      at org.mozilla.telemetry.measurement.SessionDurationMeasurement.recordSessionEnd(SessionDurationMeasurement.java:41)
//      at org.mozilla.telemetry.Telemetry.recordSessionEnd(Telemetry.java:158)
//      at org.mozilla.focus.telemetry.TelemetryWrapper.stopSession(TelemetryWrapper.kt:181)
//      at org.mozilla.focus.MainActivity.onPause(MainActivity.kt:80)
//      at android.app.Activity.performPause(Activity.java:6861)
//      at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
//      at android.app.ActivityThread.performNewIntents(ActivityThread.java:2829)
//      at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2847)
//      at android.app.ActivityThread.-wrap15(ActivityThread.java)
//      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1559)
//      at android.os.Handler.dispatchMessage(Handler.java:102)
//      at android.os.Looper.loop(Looper.java:154)
//      at android.app.ActivityThread.main(ActivityThread.java:6174)
//      at java.lang.reflect.Method.invoke(Native Method)
//      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
//      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
//
** Monkey aborted due to error.
Events injected: 2406
## Network stats: elapsed time=18913ms (0ms mobile, 0ms wifi, 18913ms not connected)
** System appears to have crashed at event 2406 of 5000 using seed 1521940338710
```

**Comment by mcomella** [comment]
This will only be reproducible with the seed if the code is the same. I forgot to record the one I reproduced with but the master 5 days later is 8ae895c24820816ccdffd6cc80ed6a4c587e66a1.

**Comment by mcomella** [comment]
Dupe #1159.
