### ISSUE TITLE
[monkey] Crash java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#720]
This low-volume crash happens in the wild (count is one-week):

![image](https://user-images.githubusercontent.com/759372/37799960-897af2ae-2dde-11e8-9a5f-024d98de5a62.png)

I think I ran this on the API 22 Android TV emulator.

```
L file line #0: Error inflating class org.mozilla.focus.iwebview.IWebView
//      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
//      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
//      at android.app.ActivityThread.access$800(ActivityThread.java:151)
//      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
//      at android.os.Handler.dispatchMessage(Handler.java:102)
//      at android.os.Looper.loop(Looper.java:135)
//      at android.app.ActivityThread.main(ActivityThread.java:5254)
//      at java.lang.reflect.Method.invoke(Native Method)
//      at java.lang.reflect.Method.invoke(Method.java:372)
//      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
//      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
// Caused by: android.view.InflateException: Binary XML file line #0: Error inflating clas
s org.mozilla.focus.iwebview.IWebView
//      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
//      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
//      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
//      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
//      at org.mozilla.focus.browser.InfoFragment.onCreateView(InfoFragment.java:40)
//      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
//      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:141
9)
//      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
//      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
//      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
//      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
//      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
//      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
//      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
//      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
//      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
//      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
//      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
//      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
//      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
//      at android.app.Activity.performStart(Activity.java:6006)
//      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
//      ... 10 more
// Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter factory
//      at org.mozilla.focus.iwebview.WebViewProvider.create(WebViewProvider.kt:0)
//      at org.mozilla.focus.browser.InfoActivity.onCreateView(InfoActivity.java:89)
//      at android.app.Activity.onCreateView(Activity.java:5325)
//      at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:41)
//      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
//      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
//      ... 31 more
//
** Monkey aborted due to error.
Events injected: 2658
## Network stats: elapsed time=21520ms (0ms mobile, 0ms wifi, 21520ms not connected)
** System appears to have crashed at event 2658 of 5000 using seed 1522115863508
```

**Comment by mcomella** [comment]
This will only be reproducible with the seed if the code is the same. I forgot to record the one I reproduced with but the master 5 days later is 8ae895c24820816ccdffd6cc80ed6a4c587e66a1.
