### ISSUE TITLE
Youtube DRM video not supported

### ISSUE THREAD

**Issue by sousmangoosta** [mozilla-mobile/firefox-tv#787]
When I try to play a protected content from youtube, I have a player error, this works on silk browser.
I got an ID : HH1T 63MV QYWK

Here is the logs in android studio debug mode : 

```
04/09 10:30:18: Launching app
$ adb push /Users/rclaveau/Documents/mozilla-workspace/firefox-tv/app/build/outputs/apk/amazonWebview/debug/app-amazonWebview-debug.apk /data/local/tmp/org.mozilla.tv.firefox.debug
$ adb shell pm install -t -r "/data/local/tmp/org.mozilla.tv.firefox.debug"
	pkg: /data/local/tmp/org.mozilla.tv.firefox.debug
Success


$ adb shell am start -n "org.mozilla.tv.firefox.debug/org.mozilla.focus.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Connected to the target VM, address: 'localhost:8600', transport: 'socket'
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/art: Late-enabling -Xcheck:jni
D/ActivityManager: default service binder = android.os.BinderProxy@363e883
D/ActivityManager: default service = android.app.ActivityManagerProxy@3ab41a00
I/art: Debugger is no longer active
W/ActivityThread: Application org.mozilla.tv.firefox.debug is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/art: Debugger is active
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1305)
I/ContextImpl: com.amazon.client.metrics.api registered service at i = 74
D/ProfileManager: Create ProfileManager instance
I/FrameworkJumpTable: Successfully loaded all classes
I/FrameworkJumpTable: Successfully loaded all methods
I/FrameworkJumpTable: Successfully loaded all fields
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
D/io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry.
D/io.sentry.android.AndroidSentryClientFactory: Sentry init with ctx='org.mozilla.focus.FocusApplication@b1bca59' and dsn='Dsn{uri=noop://localhost}'
W/io.sentry.android.AndroidSentryClientFactory: *** Couldn't find a suitable DSN, Sentry operations will do nothing! See documentation: https://docs.sentry.io/clients/java/modules/android/ ***
D/io.sentry.android.AndroidSentryClientFactory: Using buffer dir: /data/data/org.mozilla.tv.firefox.debug/cache/sentry-buffered-events
W/com.amazon.android.webkit.AmazonWebKitFactories: Create WebKitFactoryByName failed: com.amazon.android.webkit.embedded.EmbeddedWebKitFactory
I/com.amazon.android.webkit.android.ClientApiLevel: Client API Level:1
I/com.amazon.android.webkit.AmazonWebKitFactories: Successfully create WebKitFactory by name: com.amazon.android.webkit.android.AndroidWebKitFactory
I/com.amazon.android.webkit.AmazonWebKitFactories: Successfully found API level for factory:com.amazon.android.webkit.android.AndroidWebKitFactory level:2
I/com.amazon.android.webkit.android.ClientApiLevel: Client API Level:2
W/linker: /system/app/AmazonWebView/lib/arm64/libwebviewextchromium.so: unused DT entry: type 0x6ffffffe arg 0x39cf0
W/linker: /system/app/AmazonWebView/lib/arm64/libwebviewextchromium.so: unused DT entry: type 0x6fffffff arg 0x3
I/WebViewFactory: Loading com.amazon.webview.chromium version 55.5260.2883.91.282 (code 999999999)
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
I/cr_LibraryLoader: Time to load native libraries: 9 ms (timestamps 4561-4570)
I/cr_LibraryLoader: Expected native library version number "55.0.2883.91", actual native library version number "55.0.2883.91"
W/ResourceType: Attempt to retrieve bag 0x0103003e which is invalid or in a cycle.
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
E/empty: [BWC E](24922): start(): vendor/mediatek/proprietary_mt8173/platform/mt8173/hardware/bwc/bandwidth_control_port.cpp@53: Open SMI(/dev/MTK_SMI) driver file failed.:Permission denied
I/HAL: loaded HAL id=hwcomposer path=/system/lib64/hw/hwcomposer.mt8173.so hmi=0x0 handle=0x7f86b39008
I/HAL: loaded HAL id=gralloc path=/vendor/lib64/hw/gralloc.mt8173.so hmi=0x7f8c396000 handle=0x7f7eb1ad28
D/Atlas: Validating map...
I/art: Background sticky concurrent mark sweep GC freed 98538(3MB) AllocSpace objects, 3(56KB) LOS objects, 0% free, 15MB/15MB, paused 6.172ms total 100.423ms
I/HAL: loaded HAL id=gralloc path=/vendor/lib64/hw/gralloc.mt8173.so hmi=0x0 handle=0x7f7eb1ad28
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Enabling debug mode 0
I/HAL: loaded HAL id=gralloc path=/vendor/lib64/hw/gralloc.mt8173.so hmi=0x558f391d40 handle=0x7f7eb1ad28
W/PathParser: Points are too far apart 4.311470466432506
W/PathParser: Points are too far apart 4.0066767288508425
W/PathParser: Points are too far apart 4.02287445735837
W/PathParser: Points are too far apart 4.006461712974482
W/PathParser: Points are too far apart 4.147397573090075
W/IInputConnectionWrapper: setSelection on inactive InputConnection
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.amazon.android.webkit.android.AndroidWebViewDelegate$3>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.amazon.android.webkit.android.AndroidWebViewDelegate$3>
I/cr_LibraryLoader: Expected native library version number "55.0.2883.91", actual native library version number "55.0.2883.91"
I/chromium: [INFO:library_loader_hooks.cc(163)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
I/cr_AWVDeploymentClient: bindService status: true
W/cr_media: Requires BLUETOOTH permission
I/cr_Ime: ImeThread is not enabled.
E/com.amazon.android.webkit.android.AndroidWebViewDelegate: Method not supported in Android WebView
                                                            java.lang.UnsupportedOperationException
                                                                at com.amazon.android.webkit.android.AndroidWebViewDelegate.getWebViewReflection(AndroidWebViewDelegate.java:901)
                                                                at com.amazon.android.webkit.android.AndroidWebViewDelegate.onResume(AndroidWebViewDelegate.java:383)
                                                                at com.amazon.android.webkit.AmazonWebView.onResume(AmazonWebView.java:826)
                                                                at org.mozilla.focus.iwebview.IWebViewLifecycleFragment.onResume(IWebViewLifecycleFragment.kt:76)
                                                                at android.support.v4.app.Fragment.performResume(Fragment.java:2401)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1465)
                                                                at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5483)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
D/GeckoLocales: No selected locale. No correction needed.
I/Choreographer: Skipped 48 frames!  The application may be doing too much work on its main thread.
D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
E/chromium: [ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver
E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities: Unsupported mime video/mpeg2
W/AudioCapabilities: Unsupported mime audio/ac3
W/AudioCapabilities: Unsupported mime audio/eac3
W/AudioCapabilities: Unsupported mime audio/eac3-joc
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/CRLSetManager: getInstance binder: android.os.BinderProxy@1643f540
D/CRLSetManager: getInstance binder: android.os.BinderProxy@1643f540
I/cr_DeployClientHandler: should fallback to Visualon: false
I/cr_AWVDeploymentClient: disconnectRemote
D/CRLSetManager: getInstance binder: android.os.BinderProxy@1643f540
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 24922
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 24922
W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client
D/CRLSetManager: getInstance binder: android.os.BinderProxy@1643f540
D/CRLSetManager: getInstance binder: android.os.BinderProxy@1643f540
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 24922
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 24922
D/CRLSetManager: getInstance binder: android.os.BinderProxy@1643f540
D/CRLSetManager: getInstance binder: android.os.BinderProxy@1643f540
E/chromium: [ERROR:aw_autofill_client.cc(185)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
D/CRLSetManager: getInstance binder: android.os.BinderProxy@1643f540
W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client
D/CRLSetManager: getInstance binder: android.os.BinderProxy@1643f540
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 24922
E/chromium: [ERROR:aw_autofill_client.cc(185)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.media.MediaDrmBridge$ExpirationUpdateListener>
I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.media.MediaDrmBridge$ExpirationUpdateListener>
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 2) = {
                string name = "audio/opus"
                int32_t nameIsType = 1
                int32_t encoder = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: onAllocateComponent mime=audio/opus
D/ACodec: onAllocateComponent tmpMime=audio/opus
D/ACodec: [SVP] onAllocateComponent, match size=1
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 1) = {
            string mime = "audio/opus"
            int32_t encoder = 0
          }
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 5) = {
                string name = "audio/vorbis"
                int32_t nameIsType = 1
                int32_t encoder = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: onAllocateComponent mime=audio/vorbis
D/ACodec: onAllocateComponent tmpMime=audio/vorbis
D/ACodec: [SVP] onAllocateComponent, match size=1
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 4) = {
            string mime = "audio/vorbis"
            int32_t encoder = 0
          }
E/cr_MediaCodecUtil: Decoder for type video/x-vnd.on2.vp8 is not supported on this device
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 8) = {
                string name = "video/x-vnd.on2.vp9"
                int32_t nameIsType = 1
                int32_t encoder = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: onAllocateComponent mime=video/x-vnd.on2.vp9
D/ACodec: onAllocateComponent tmpMime=video/x-vnd.on2.vp9
D/ACodec: [SVP] onAllocateComponent, match size=2
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 7) = {
            string mime = "video/x-vnd.on2.vp9"
            int32_t encoder = 0
          }
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 11) = {
                string name = "audio/mp4a-latm"
                int32_t nameIsType = 1
                int32_t encoder = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: onAllocateComponent mime=audio/mp4a-latm
D/ACodec: onAllocateComponent tmpMime=audio/mp4a-latm
D/ACodec: [SVP] onAllocateComponent, match size=1
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 10) = {
            string mime = "audio/mp4a-latm"
            int32_t encoder = 0
          }
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 14) = {
                string name = "video/avc"
                int32_t nameIsType = 1
                int32_t encoder = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: onAllocateComponent mime=video/avc
D/ACodec: onAllocateComponent tmpMime=video/avc
D/ACodec: [SVP] onAllocateComponent, match size=2
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 13) = {
            string mime = "video/avc"
            int32_t encoder = 0
          }
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 17) = {
                string name = "audio/opus"
                int32_t nameIsType = 1
                int32_t encoder = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: onAllocateComponent mime=audio/opus
D/ACodec: onAllocateComponent tmpMime=audio/opus
D/ACodec: [SVP] onAllocateComponent, match size=1
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 16) = {
            string mime = "audio/opus"
            int32_t encoder = 0
          }
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 20) = {
                string name = "audio/vorbis"
                int32_t nameIsType = 1
                int32_t encoder = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: onAllocateComponent mime=audio/vorbis
D/ACodec: onAllocateComponent tmpMime=audio/vorbis
D/ACodec: [SVP] onAllocateComponent, match size=1
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 19) = {
            string mime = "audio/vorbis"
            int32_t encoder = 0
          }
E/cr_MediaCodecUtil: Decoder for type video/x-vnd.on2.vp8 is not supported on this device
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 23) = {
                string name = "OMX.MTK.VIDEO.DECODER.VP9"
                int32_t nameIsType = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 22) = {
            string componentName = "OMX.MTK.VIDEO.DECODER.VP9"
          }
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 26) = {
                string name = "OMX.MTK.VIDEO.DECODER.VP9.secure"
                int32_t nameIsType = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 25) = {
            string componentName = "OMX.MTK.VIDEO.DECODER.VP9.secure"
          }
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 29) = {
                string name = "audio/mp4a-latm"
                int32_t nameIsType = 1
                int32_t encoder = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: onAllocateComponent mime=audio/mp4a-latm
D/ACodec: onAllocateComponent tmpMime=audio/mp4a-latm
D/ACodec: [SVP] onAllocateComponent, match size=1
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 28) = {
            string mime = "audio/mp4a-latm"
            int32_t encoder = 0
          }
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 32) = {
                string name = "OMX.MTK.VIDEO.DECODER.AVC.secure"
                int32_t nameIsType = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 31) = {
            string componentName = "OMX.MTK.VIDEO.DECODER.AVC.secure"
          }
D/MediaCodec: [SVP] MediaCodec::Init=AMessage(what = 'init', target = 35) = {
                string name = "OMX.MTK.VIDEO.DECODER.AVC.secure.secure"
                int32_t nameIsType = 0
              }
I/OMXClient: Using client-side OMX mux.
D/ACodec: [SVP] msg=AMessage(what = 'allo', target = 34) = {
            string componentName = "OMX.MTK.VIDEO.DECODER.AVC.secure.secure"
          }
W/ACodec: Allocating component 'OMX.MTK.VIDEO.DECODER.AVC.secure.secure' failed, try next one.
E/ACodec: Unable to instantiate codec 'OMX.MTK.VIDEO.DECODER.AVC.secure.secure'.
E/ACodec: signalError(omxError 0x80001003, internalError -2147483648)
E/MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
I/MediaCodec: MediaCodec:MMSW_Metrics5.2.6.2:FailBeforePlayback.DecoderErrorFatal=1;CT;1:NR
W/MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
E/cr_MediaCodecUtil: Failed to create MediaCodec: video/avc, isSecure: true, requireSoftwareCodec: no
                     java.lang.IllegalArgumentException: Failed to initialize OMX.MTK.VIDEO.DECODER.AVC.secure.secure, error 0xfffffffe
                         at android.media.MediaCodec.native_setup(Native Method)
                         at android.media.MediaCodec.<init>(MediaCodec.java:489)
                         at android.media.MediaCodec.createByCodecName(MediaCodec.java:473)
                         at org.chromium.media.MediaCodecUtil.createDecoder(MediaCodecUtil.java:212)
                         at org.chromium.media.MediaCodecUtil.canDecode(MediaCodecUtil.java:159)
I/chromium: [INFO:CONSOLE(4586)] "It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.", source:  (4586)
```

**Comment by mcomella** [comment]
@sousmangoosta Thanks for the report - do you have a URL as an example of protected content on Youtube? Does this only affect either tv.youtube.com or youtube movie purchases?

**Comment by sousmangoosta** [comment]
@mcomella : It's a youtube movie purchase, eg: https://www.youtube.com/watch?v=Md6EgfXoDfY .
But I think there is no DRM for the preview content.

**Comment by Sdaswani** [comment]
I'm pretty sure this is due to [not being able to support 4k content yet ](https://github.com/mozilla-mobile/firefox-tv/issues/277)- I can play some purchases, but for the recent purchases which are 4k, I can't play either.

**Comment by sousmangoosta** [comment]
@Sdaswani : It's not 4k, it's 720p @24fps max with widevine on my desktop firefox browser with codecs avc / mp4a.

**Comment by Sdaswani** [comment]
Understood @sousmangoosta - let us check some things internally and we will follow up on this issue.

**Comment by AaronMT** [comment]
Slight hunch that a video player 

@sousmangoosta Can you try rebooting your device and then trying to play a video in Firefox without starting Silk? It is possible that the Fire TV Stick only supports single player instantiation and it wasn't released?

**Comment by sousmangoosta** [comment]
@AaronMT : I installed Silk after playback issue to verify if it works on Silk, but I'll try and let you know.

**Comment by sousmangoosta** [comment]
@AaronMT : I uninstalled Silk, clear data on Firefox, reboot, choose no turbo mode, try again to load the movie, same issue.

**Comment by AaronMT** [comment]
Thanks for checking.

**Comment by sousmangoosta** [comment]
For my opinion, by default the webview use the default Android MediaPlayer who not have DRM.
We need to use Amazon port of Exoplayer to support DRM : https://developer.amazon.com/fr/docs/fire-tv/media-players.html#exoplayer

**Comment by liuche** [comment]
This should be fixed by #379 from other discussions, but we should keep this open and verify that it works once we switch to the system webview.

**Comment by mcomella** [comment]
The Android TV docs mention "media format support" including DRM: https://developer.android.com/training/tv/start/start#media

**Comment by bbinto** [comment]
@mcomella - can you confirm what the lastest status is?

**Comment by mcomella** [comment]
@npark-mozilla Can you test this and let us know how it's working?

I have no experience testing this and have my hands full at the moment.

**Comment by npark-mozilla** [comment]
@mcomella sure, so we can rent a video on youtube, and try to play that on fire TV and see whether it works.

**Comment by sousmangoosta** [comment]
I tried again, and it's not works on my side.

**Comment by npark-mozilla** [comment]
Since #379 is still open, I think we need to wait until it is in master?

**Comment by liuche** [comment]
We're now on the System WebView on master, so this is unblocked now.

**Comment by liuche** [comment]
@rpappalax can you take a look at this along with #277 ?

**Comment by sousmangoosta** [comment]
@liuche : Don't works better on my side on master branch

**Comment by Sdaswani** [comment]
I have confirmed we still can't play DRM'ed content.

**Comment by mcomella** [comment]
FYI SF office devs: I have DRM content purchased so you can use my account to reproduce the issue. https://bitmovin.com/demos/drm also seems to be effective.

---

On Echo Show, we also can't play DRM content but trying to results in a crash. In order to play DRM content, we're supposed to listen for the `WebChromeClient.onPermissionRequest` callback and grant the RESOURCE_PROTECTED_MEDIA_ID permission: https://developer.android.com/reference/android/webkit/WebChromeClient#onPermissionRequest(android.webkit.PermissionRequest)

On Echo Show, this results in a crash where not granting the permission crashes (stack trace: "expected grant() or deny()") or granting the permission crashes (stack trace: "grant() or deny() called twice") but I don't know if we'd run into the same problem. See https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/548#issuecomment-430435712 for all the juicy details.

**Comment by dnarcese** [comment]
I've tried listening to the callback and then showing a dialog to accept or deny. On clicking 'accept', I grant the RESOURCE_PROTECTED_MEDIA_ID permission- this results in the following crash saying that grant() or deny() has been already called: 
```10:46:14.513 9959-9959/org.mozilla.tv.firefox.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.tv.firefox.debug, PID: 9959
    java.lang.IllegalStateException: Either grant() or deny() has been already called.
        at org.chromium.android_webview.permission.AwPermissionRequest.validate(AwPermissionRequest.java:105)
        at com.android.webview.chromium.WebViewContentsClientAdapter$PermissionRequestAdapter.grant(WebViewContentsClientAdapter.java:4075)
        at mozilla.components.browser.engine.system.SystemEngineView$createWebChromeClient$1$createDialog$2.onClick(SystemEngineView.kt:307)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6188)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)

**Comment by Sdaswani** [comment]
I feel like @mcomella saw this on Show too? Or is this different?

https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/548#issuecomment-430435712

**Comment by dnarcese** [comment]
@Sdaswani I fixed the crash (see [edited comment](https://github.com/mozilla-mobile/firefox-tv/issues/787#issuecomment-431873245)). So now this is different from what is happening on Show.

**Comment by dnarcese** [comment]
The same behaviour is seen on Silk: 
Visiting https://bitmovin.com/demos/drm prompts the permission request dialog, but on clicking Accept, the video content still does not show.

Going to test with a purchased YouTube video next.

**Comment by dnarcese** [comment]
Purchased YouTube video plays correctly with the new request dialog. This change is needed in android-components, will file a bug.

**Comment by liuche** [comment]
The 0.29 version of a-c comes out 10/29, so that will be Monday and this will miss the sprint. @athomasmoz should we move this to the 3.1-Backlog? It looks like the PR is open in a-c and it just needs to be merged and we need to pull the next version of a-c in.

**Comment by Sdaswani** [comment]
Can we put it in the next sprint?

**Comment by athomasmoz** [comment]
Yep, I'll put it at the top of the 3.1 backlog, which we'll pull from for next sprint

**Comment by pocmo** [comment]
Removing a-c label: Patch will be in 0.29.0.

**Comment by athomasmoz** [comment]
0.29.0 now available, removing the 'blocked' label

**Comment by sousmangoosta** [comment]
I can confirm it's ok with a-c 0.29

**Comment by Sdaswani** [comment]
talking to @HiralSModi - certain DRM will work, but not all DRM will work. platform fix is required all DRM types. re-opening to track that platform work. Hiral to provide list of supported media soon.
