### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void okhttp3.Cache.evictAll()' on a null object reference

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#957]
The type signature is incorrect, it seems: `Cache` can return null:
```kotlin
try { client.cache().evictAll() } catch (_: IOException) { /* We don't care. */ }
```

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void okhttp3.Cache.evictAll()' on a null object reference
        at org.mozilla.focus.utils.OkHttpWrapper.onLowMemory(OkHttpWrapper.kt:16)
        at org.mozilla.focus.FocusApplication.onLowMemory(FocusApplication.java:60)
        at android.app.ActivityThread.handleLowMemory(ActivityThread.java:4343)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
```

This happened on a Fire Stick while fast-forwarding and rewinding Youtube shortly after rebooting the device.

**Comment by mcomella** [comment]
For this bug:
- Update OkHttp to the latest version, which I think will cause the build to break because it adds the appropriate `@Nullable` annotation
- Fix the compile error (or the issue if not)
